### ISSUE TITLE
JTCalendarDayView selection API

### ISSUE THREAD

**Issue by mozharovsky** [jonathantribouharet/JTCalendar#10]
Hello Jonathan,

Thank you for such a nice calendar. It might be even better, if there was an explicit way of selecting a date (simple adding a CircleView onto the day one). I hope you find this feature useful to work on. 

Thank you and happy coding time! :+1:

**Comment by rabhishek** [comment]
Hi, 
I have  successfully integrated  JTCalendaer  with pods in my new Project (swift) and able to run in device, but when i try to archive its showing '**JTCalendar/JTCalendar.h' file not found error.**

**Comment by adiusu** [comment]
> Hi,
> I have successfully integrated JTCalendaer with pods in my new Project (swift) and able to run in device, but when i try to archive its showing 'JTCalendar/JTCalendar.h' file not found error.
> My xcode version is 7.3.1
> Thanks!

**I have the same problem with same XCode version. Any Solution?**
