### ISSUE TITLE
How did I enable the scrolling for contentView or MenuView?

### ISSUE THREAD

**Issue by seanLee** [jonathantribouharet/JTCalendar#100]
Thx for the awesome calendar.But I hava some questions about using it:
did I have some ways to enable the scrolling? I set userInteractionEnabled = No.But it can't respons for the call ````- (void)calendarDidDateSelected:(JTCalendar *)calendar date:(NSDate *)date````.And I need two buttons to make it paged like the scrolling did?How can I do that?

**Comment by jonathantribouharet** [comment]
The scroll is enabled by default, if you can't scroll I think you have to check to contraints of your views.
If you set `userInteractionEnabled` to NO, you can't interact with the view so you can't scroll.
I didn't understand your question about `calendarDidDateSelected`.
And for the button you have `loadPreviousPage` and `loadNextPage` methods for the object `JTCalendar`.

**Comment by seanLee** [comment]
Oh,so sorry about my question.I mean set the enable = no for the scrollView.I don't want to scroll them but just page the by the button.

**Comment by jonathantribouharet** [comment]
So you want to disable the scroll, so like for any scrollview set `scrollEnabled`to `NO` for the contentView and the menuView.

**Comment by seanLee** [comment]
yeah,I find other place to set the scrollEnabled to Yes.It's in the ````reloadAppearance```.First I didn't find this.Thank u much,now I get what I wanted.
