### ISSUE TITLE
Change Date Formatter

### ISSUE THREAD

**Issue by ankitgoyalapplify** [jonathantribouharet/JTCalendar#102]
Hello,

Is it possible to change date formatter of calendar?. Actually, I just want to change dates like 01,02 to 09 to 1, 2 to 9. So, Can you please describe how can it be achieved?

**Comment by jonathantribouharet** [comment]
Check calendar.calendarAppearance, you have a `weekDayFormat` options for that.

**Comment by guilhermearaujo** [comment]
@jonathantribouharet what about the menu month view? I'd like it to include the year (e.g. November 2015).

**Comment by ankitgoyalapplify** [comment]
calendar1.calendarAppearance.monthBlock = ^NSString *(NSDate *date, JTCalendar *jt_calendar)
    {
        
        NSCalendar *calendar = jt_calendar.calendarAppearance.calendar;
        NSDateComponents *comps = [calendar components:NSCalendarUnitYear|NSCalendarUnitMonth fromDate:date];
        NSInteger currentMonthIndex = comps.month;
        
        static NSDateFormatter *dateFormatter;
        if(!dateFormatter)
        {
            dateFormatter = [NSDateFormatter new];
            dateFormatter.timeZone = jt_calendar.calendarAppearance.calendar.timeZone;
        }
        
        while(currentMonthIndex <= 0)
        {
            currentMonthIndex += 12;
        }
        
        NSString *monthText = [[dateFormatter standaloneMonthSymbols][currentMonthIndex - 1] capitalizedString];
        
        return [NSString stringWithFormat:@"%@ %ld ", monthText, (long)comps.year];
    };

**Comment by guilhermearaujo** [comment]
Thanks @ankitgoyalapplify. I got it even shorter:

```
[appearance setMonthBlock:^NSString *(NSDate *date, JTCalendar *calendar) {
  NSDateFormatter *formatter = [NSDateFormatter new];
  [formatter setDateFormat:@"MMMM YYYY"];
  return [[formatter stringFromDate:date] capitalizedString];
}];
```
