### ISSUE TITLE
 Change the color of Saturdays and Sundays

### ISSUE THREAD

**Issue by MilapKundalia** [jonathantribouharet/JTCalendar#106]
Hi,

I want to change the color of Saturdays and Sundays in Month and Week view can you please help me!!!

Thanks

**Comment by jonathantribouharet** [comment]
Not currently possible but in the next version (don't know when).

**Comment by MilapKundalia** [comment]
Thanks Jonathan 
Waiting for the updated version

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

Sorry for the delay, you can do this in `prepareDayView` method.

**Comment by dungnvfso17** [comment]
# * Add method:
- (int)getWeekDayNumberFromNSDate:(NSDate *)date {
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"e"];
    NSInteger weekdayNumber = (NSInteger)[[dateFormatter stringFromDate:date] integerValue];
    
    return (int)weekdayNumber;
}

# In - (void)calendar:(JTCalendarManager *)calendar prepareDayView:(JTCalendarDayView *)dayView in // Another day of the current month

please add: 
// Another day of the current month
    else{
        dayView.circleView.hidden = YES;
        dayView.dotView.backgroundColor = [Common colorWithHexString:@"16bc00"];
        dayView.textLabel.textColor = [UIColor blackColor];
        
        
        **//display date color
        int numberDayOfWeek = [self getWeekDayNumberFromNSDate:dayView.date];
        if (numberDayOfWeek == 1) {
            dayView.textLabel.textColor = [Common colorWithHexString:@"ff0000"];
        } else if (numberDayOfWeek == 7) {
            dayView.textLabel.textColor = [Common colorWithHexString:@"4e96d9"];
        }**
        
    }

In here, I write a method to convert hex color to UIColor, you can choose color you want
