### ISSUE TITLE
Month scroll right two at a time

### ISSUE THREAD

**Issue by alextov** [jonathantribouharet/JTCalendar#107]
When I scroll months by swiping to the right on months view, they scroll two at a time. It works fine when swiping left or when swiping right on the calendar itself. Here's a video demonstration: https://gfycat.com/UnfoldedCanineClownanemonefish

**Comment by jonathantribouharet** [comment]
Thank you, I noticed this bug, it's because I use `pagingEnabled` of the UIScrollView.
#65
