### ISSUE TITLE
Multiple calendar views in a view controller will update selected day simultaneously

### ISSUE THREAD

**Issue by dfithian** [jonathantribouharet/JTCalendar#111]
I have a form which takes in a start and end date. Both the start and end dates use the calendar view. When I touch a day on one of the calendars, the day is selected on both calendars (due to the method didDaySelected:(NSNotification *)notification getting called). Is there any way to reload the current day selected?

**Comment by jonathantribouharet** [comment]
It's a bad conception from me. For now, you can hack by saving the current day selected and restore it by sending a notification named `kJTCalendarDaySelected` with the date in `object`.

    [[NSNotificationCenter defaultCenter] postNotificationName:@"kJTCalendarDaySelected" object:date];

**Comment by dfithian** [comment]
Okay, I found a workaround. Seems pretty terrible based on what you said about reloadAppearance.

Asynchronously process reloadData and reloadAppearance calls:

```swift
    override func viewDidLoad() {
        //...
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "reloadAppearance:", name: "reload", object: nil)
    }
    func calendarDidDateSelected(calendar: JTCalendar!, date: NSDate!) {
        self.delegate?.dateDidSelect(self, date: date)
        NSNotificationCenter.defaultCenter().postNotificationName("reload", object: nil)
    }
    func reloadAppearance(notification: NSNotification) {
        self.calendar.reloadData()
        self.calendar.reloadAppearance()
    }
```

**Comment by jonathantribouharet** [comment]
The documentation is not up to date, I did some changes. I m preparing a new version, fully rewrite. Check the code, it's pretty simple.

**Comment by dfithian** [comment]
Hmm, I think that's the source of my problem, not the solution. The problem is that both calendar views are observing the ```kJTCalendarDaySelected``` notification, so if I post it with a date, both will get updated.

**Comment by jonathantribouharet** [comment]
I know it's the source of the problem that's why I said It's a bad conception from me. If you display both calendars in the same time, I don't see any solution.

**Comment by dfithian** [comment]
Ahah. Thanks for your time. Seems like my workaround is okay for now.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

This bug should be gone.
