### ISSUE TITLE
Translation from Objective-C to Swift

### ISSUE THREAD

**Issue by ishawn** [jonathantribouharet/JTCalendar#117]
Hi, I tried to translate Objective-C codes to Swift codes. And after import "JTCalendar.h", I cannot find setMenuMonthsView, setContentView, and setDataSource in Swift.
I tried to add them into "JTCalendar.h", but still doesn't work.

**Comment by jonathantribouharet** [comment]
I suppose you did something wrong, I can't help you I don't use Swift.
