### ISSUE TITLE
How can I receive event when moved to next/prev month?

### ISSUE THREAD

**Issue by gamoo** [jonathantribouharet/JTCalendar#118]
When user change the month on the JTCalendar, how can I receive changed-month event?
The related event or method doesn't defined on the JTCalendarDataSource;
Can I override loadPreviousMonth or loadNextMonth on JTCalendar?
If possible method, tell me please.

**Comment by jonathantribouharet** [comment]
I think you miss something in `JTCalendarDataSource`, there are `calendarDidLoadPreviousPage` and `calendarDidLoadNextPage` methods.
