### ISSUE TITLE
Getting list of Week days(Dates in array or any format) from the week view

### ISSUE THREAD

**Issue by parvezbelim** [jonathantribouharet/JTCalendar#119]
I have implemented the JTCalendar, it is really amazing. It works smoothly and having high level of efficiency. I have requirement in which I need to get the list of dates in any date format, when user changes the week in week view.

Is that possible ? 

Thanks in advance

**Comment by jonathantribouharet** [comment]
You need a list of which dates? The visible dates?
If yes, with the `currentDate` you have a day in the week (not a specific day it can be any day in the week). After you take the first days of the week and the last day and you have your list of dates.
Is that what you want?

**Comment by parvezbelim** [comment]
Well Yes ! for example in week view, you are in 2nd week of the month. So I require dates of second week. example : - Sunday, 5-4-2015,Mon 6-4-2015 .... Sat 11-4-2015.
So if that possible or some alternate solution for getting this.

**Comment by jonathantribouharet** [comment]
In the file https://github.com/jonathantribouharet/JTCalendar/blob/master/JTCalendar/JTCalendarContentView.m line 139 you have a method `- (NSDate *)beginningOfWeek:(NSDate *)date` which I think return the beginning of the week, I'm not 100% sure. Also, be careful the date are UTC so if you use NSLog you may think the date is invalid but check the hours and the timezone.
After you just have to add 7 days (or 7 times one day) with a `NSDateComponents` object and the `dateByAddingComponents` method.

**Comment by parvezbelim** [comment]
I checked this method. But the question is which date I pass in parameter ?
