### ISSUE TITLE
Displaying my calendar events

### ISSUE THREAD

**Issue by earthgeek** [jonathantribouharet/JTCalendar#12]
I'm new to calendars in iOS, so this is probably just an newbie thing. Can you give me a hint about how to read my calendar events into the calendar view? I'm sure they need to be supplied to the datasource, but in what kind of object?

Thanks,
Jeff

**Comment by Mujtabaulhasankhan** [comment]
I used your calendar it has very good UI. I need some little help from you how can I show multiple events on your calendar your calendar only show only show single events can you please help me with this and also if there is no events then user is not able to click on it.
