### ISSUE TITLE
Earlier month initially not loading

### ISSUE THREAD

**Issue by steilerDev** [jonathantribouharet/JTCalendar#121]
I am using JTCalendar in my Swift project. The problem I am experiencing is that when initially load the calendar view the view is only loading upcoming months but no preceding ones. After trying to access a preceding month the view loads it.

I created a short gif showing my problem:

![untitled](https://cloud.githubusercontent.com/assets/7031616/7069739/d0fced54-deda-11e4-8767-b9821ed8d21c.gif)

I am using the following code in my `viewDidLoad` to modify the calendar: 

    override func viewDidLoad() {
      super.viewDidLoad()    
      calendar.calendarAppearance.calendar().firstWeekday = 2
      calendar.calendarAppearance.focusSelectedDayChangeMode = true
      calendar.calendarAppearance.dayCircleColorSelected = UIColor(hex: MVColor.Primary.Dark)
      calendar.calendarAppearance.dayCircleColorSelectedOtherMonth = UIColor(hex: MVColor.Primary.Dark)
      calendar.calendarAppearance.dayCircleColorToday = UIColor(hex: MVColor.Primary.Lighter)
      calendar.calendarAppearance.dayCircleColorTodayOtherMonth = UIColor(hex: MVColor.Primary.Lighter)
      calendar.calendarAppearance.dayDotColor = UIColor.blackColor()
      calendar.calendarAppearance.dayDotColorOtherMonth = UIColor.blackColor()
      calendar.calendarAppearance.monthBlock = {
        date, jt_calendar in
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "MMMM yyyy"
        return dateFormatter.stringFromDate(date)
      }
    
      calendar.dataSource = self
      calendar.menuMonthsView = menuView
      calendar.contentView = contentView
    
      calendar.reloadData()
    }

I am not sure what else you need to find the source of the problem. Maybe you want to look at the [github repo of my project](https://github.com/steilerDev/myVerein/tree/master/Code/iOS%20Client/myVerein).

**Comment by jonathantribouharet** [comment]
Have you call `repositionViews` in `viewDidLayoutSubviews`, this part is supposed to set the scrollview to the good page. If it doesn't work, call `reloadData`in `viewDidAppear`.

**Comment by steilerDev** [comment]
Ah snap, missed that! Thanks for the help and keep up the incredible good work!

**Comment by rabhishek** [comment]
Hi,
I have successfully integrated JTCalendaer with pods in my new Project (swift) and able to run in device, but when i try to archive its showing 'JTCalendar/JTCalendar.h' file not found error.

My xcode version is 7.3.1

Thanks!

**Comment by adiusu** [comment]
> Hi,
I have successfully integrated JTCalendaer with pods in my new Project (swift) and able to run in device, but when i try to archive its showing 'JTCalendar/JTCalendar.h' file not found error.

My xcode version is 7.3.1

Thanks!

**I have the same problem with same XCode version. Any Solution?**

**Comment by anpuAnand** [comment]
can you provide sample code for JTCalender in Swift
