### ISSUE TITLE
Switch months removes day selected

### ISSUE THREAD

**Issue by aleberguer** [jonathantribouharet/JTCalendar#123]
Hi, I am setting a custom date with the notificationCenter using the line 
```objective-c
[NSNotificationCenter defaultCenter] postNotificationName:@"kJTCalendarDaySelected" object:date];
```
The problem is when I change the month, the calendar not keep the selection. The selection disappear when I go back to the original month.
Is this the expected behaviour? How can I keep the selection in the calendar?
Thank you.

**Comment by jonathantribouharet** [comment]
Not really, it's because use the notification is a hack, I put it in the README because a lot of people ask me about this feature. You need to call `[self.calendar setCurrentDateSelected:date];` also.
I updated the README.

**Comment by aleberguer** [comment]
Thank you. It is working now with the ```setCurrentDateSelected``` call .
