### ISSUE TITLE
Restrict Calendar within a range

### ISSUE THREAD

**Issue by dev-ajmehra** [jonathantribouharet/JTCalendar#125]
Hello JT 
your add on is awesome but i need some extra feature. 
can be restrict user to select date between a range like 
12/1/2001 - 12/12/2014 
i mean to say that user can only able to select date within a range

**Comment by jonathantribouharet** [comment]
`JTCalendarViewDataSource` protocol have a method `- (BOOL)calendar:(JTCalendar *)calendar canSelectDate:(NSDate *)date;`.
You just have to implement it.
