### ISSUE TITLE
How do i change the "Todays date" circle  color to green when i clicked "Today button".

### ISSUE THREAD

**Issue by nnaavveenn35** [jonathantribouharet/JTCalendar#130]
Hi,

One more doubt, when i clicked "today button" am expecting it will take me to todays date and its working perfectly in your code . but here i need one more option like when i click on " today button"  i need to change the color of "today date" to green instead of blue and "deselect al other dates". how do i do this?

**Comment by jonathantribouharet** [comment]
You want to simulate a touch on the date, so currently there is a hack (it's in the readme):

	// Update views
	[NSNotificationCenter defaultCenter] postNotificationName:@"kJTCalendarDaySelected" object:date];

	// Store currentDateSelected
	[self.calendar setCurrentDateSelected:date];

**Comment by nnaavveenn35** [comment]
Thank you ,  is there any way to change that default blue color for today to green when we click today

**Comment by jonathantribouharet** [comment]
Yes, check in https://github.com/jonathantribouharet/JTCalendar/blob/master/JTCalendar/JTCalendarAppearance.h
There are a lot of properties you can change. You can change today color or the color of selected day but not specifically today when it's selected, it will come in a next version (don't have a date for this version).

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
