### ISSUE TITLE
Date range start from today

### ISSUE THREAD

**Issue by marcoiacobelli** [jonathantribouharet/JTCalendar#131]
Hi JT,
tnx for this library, soo cool, I love it! There is a way to setup a range of date taken from an int (numer of days) and show only the date in range?
Tnxs a lot.
mj

**Comment by jonathantribouharet** [comment]
No sorry, but you're not the only one to ask for this.

**Comment by marcoiacobelli** [comment]
Ok, tnxs! ;)

On Tuesday, April 28, 2015, Jonathan Tribouharet <notifications@github.com>
wrote:

> No sorry, but you're not the only one to ask for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonathantribouharet/JTCalendar/issues/131#issuecomment-97103303>
> .
>


-- 
--
dott. Marco Iacobelli
Mobile Engineer

ITMakers <https://www.facebook.com/pages/ITMakers/477482962305480?fref=ts>ITALIA

cel. +39 373 5389164

**Comment by palcalde** [comment]
@marcoiacobelli I have a forked version of this repo that allows to select a range of dates. it was a need for my current project and I made the needed changes for it. Take a look at: https://github.com/palcalde/JTCalendar

**Comment by marcoiacobelli** [comment]
Great job!
tnxs


dott. Marco Iacobelli
Mobile Engineer

ITMakers <https://www.facebook.com/pages/ITMakers/477482962305480?fref=ts>ITALIA

cel. +39 373 5389164


*ATTENTION*:
This e-mail message contains confidential information intended solely for
the person to whom it is addressed. If you are not the intended recipient,
you are hereby notified that any disclosure, copying, distribution of the
contents of this e-mail message is strictly prohibited. If you have
received this communication in error, please delete it immediately and call
us collect to let us know it. Thank you.


*ATTENZIONE*: Le informazioni contenute nella presente comunicazione
possono essere riservate e sono comunque destinate esclusivamente alle
persone sopraindicate. Nel caso in cui il presente messaggio venga ricevuto
da persona diversa dal destinatario si avverte che ne sono proibite la
diffusione, la distribuzione nonché l'estrazione di copia. Nel caso aveste
ricevuto il presente messaggio per errore Vi preghiamo informarci
immediatamente per telefono e di eliminarlo dal vostro computer. Grazie.


2015-06-25 16:42 GMT+02:00 Pablo Alcalde <notifications@github.com>:

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
