### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by bursuc** [jonathantribouharet/JTCalendar#132]
Is there a way to change the language of the calendar without changing the language of the phone?

**Comment by jonathantribouharet** [comment]
Currently no, sorry.

**Comment by jonathantribouharet** [comment]
Let it open, I will add this feature later.

**Comment by bursuc** [comment]
Ok, it will be very nice for me. Thanks

**Comment by fjcaetano** [comment]
I believe I managed it by simply adding a `NSLocale` property to `JTCalendarAppearance`.

Whenever a `NSDateFormatter` is instantiated I set its locale. It is working for me. I forgot to formally test it and write test cases for it, though.

**Comment by gpDB** [comment]
I searched the code what you posted but I don't find it, I think your modifications are made on old version of JTCalendar.

**Comment by fjcaetano** [comment]
@gpDB, I forked the master last week and worked on top of it. The link for my commit is right here, however, I haven't asked for a pull-request yet.

Maybe that's what is confusing.

**Comment by fjcaetano** [comment]
Actually, my solution is similar to the pull-request #104

**Comment by gpDB** [comment]
@fjcaetano Thanks, the solution proposed by you, worked perfect.

**Comment by gpDB** [comment]
@fjcaetano But I have a problem in my application where I have option to change language of application from same controller where I use calendar until noiw I succeded to change days name but for month doesn't work. Do you have any idea, how can achieve this?

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

With `settings.calendar.locale` and `settings.calendar.timeZone`.
