### ISSUE TITLE
Setting the height of the calendar, or row height?

### ISSUE THREAD

**Issue by Jules2010** [jonathantribouharet/JTCalendar#134]
I'm not able to use storyboards at the time, due to development time.
Although I am using autolayout with interface builder.

I've set the calendar content view to 300 height, however the control doesn't seem to obey this.

I want to have a table view underneath to show items on that day.

I think the code is modifying the height as the bottom row is missing overlaps.

I've tried making the content view bigger but I think the calendar expands.

I tried to copy the example but that has height 300 too.

help!

**Comment by jonathantribouharet** [comment]
The calendar doesn't change its height itself, it's against the logic of a view.
The row height (each week) take all space available.
I think you have a problem with your contraints but it's not related to the calendar, try to replace JTCalendarContentView by a UIScrollView if you want to be sure.

PS: I use neither the storyboard nor interface builder, I do everything in code with Masonry (https://github.com/SnapKit/Masonry).

**Comment by simon-teeps** [comment]
@jonathantribouharet Any idea on how to make the calendar show 10 weeks at a time (e.g. smaller calendar week rows)? I have looked through the code.. It seems the calendar maxes out at 6 weeks.
