### ISSUE TITLE
How to change weekDayTextColor for Today.

### ISSUE THREAD

**Issue by karuppub** [jonathantribouharet/JTCalendar#135]
I set dayTextColorToday for today date in blue , like i want to set weekDayTextColor   for today in blue.

**Comment by jonathantribouharet** [comment]
Sorry you currently can't do this. There is no `weekDayTextColor` just for today, it's coming in the next version.

**Comment by karuppub** [comment]
Thank you for your response, and i want to know is it possible to set  setCurrentDateSelected  in calendarDidLoadNextPage and calendarDidLoadPreviousPage. if it's possible please give me some example.

**Comment by jonathantribouharet** [comment]
I see want you wanna do, the only way now is by doing:

    [NSNotificationCenter defaultCenter] postNotificationName:@"kJTCalendarDaySelected" object:date];

**Comment by karuppub** [comment]
Thanks , See How to pass the date when i swipe to next page or previous page in which you mentioned above.

**Comment by karuppub** [comment]
Hi, I achieved above one with passing self.calendar.currentDate in  [NSNotificationCenter defaultCenter] postNotificationName:@"kJTCalendarDaySelected" object:self.calendar.currentDate];

Now, I need know to get the visible week first day.
For your understanding, see today Wednesday  date 06-may-2015. when i swipe to next page i am getting Wednesday 13-may-2015 but i want to get monday 11-may-2015.

**Comment by jonathantribouharet** [comment]
For that use [NSDateComponents](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSDateComponents_Class/index.html).

**Comment by karuppub** [comment]
Thanks for Your valuable response, I have completed.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
