### ISSUE TITLE
How can I provide a minimum and maximum month which can be scrolled to?

### ISSUE THREAD

**Issue by Jules2010** [jonathantribouharet/JTCalendar#136]
Hi,

I would like to stop people from scrolling to months before and after certain dates, perhaps the first of said months.

I've seen that I can use canSelectDate to stop people from selecting dates, but I'd  months / dates beyond and before a maximum / minimum date not to be visible?

e.g. Don't disable after January 2017 or before December 2013.

Can you talk me through how I can achieve this, if it's possible?

I did see someone has posted this..
https://gist.github.com/HaloZero/66fec90151503d09f9c9
... but I don't have a panning view, don't want to have my own version of the pod, as I don't feel confident making changes to it.

Thanks so much for your great control :)

Jules.

**Comment by jonathantribouharet** [comment]
Currently it's not possible, but you're not the first to ask for it.

**Comment by Jules2010** [comment]
Hmmm, how about being able to disable the scrolling on the month bar?
Then I could just add some next / previous buttons?

**Comment by jonathantribouharet** [comment]
You can do it, I just don't have the time now.

**Comment by Jules2010** [comment]
Ah right, wasn't sure that would exposed.
Can you briefly summarize what I would need to do?

Thanks
:)

**Comment by Jules2010** [comment]
Ahhhh after reloaddata in viewdidload...

[self.calendarMenuView setScrollEnabled:NO];

**Comment by Jules2010** [comment]
I can this in my next a previous buttons now I've turned off scrolling, I have an example of this here... https://github.com/Jules2010/JTCalendar
