### ISSUE TITLE
Week view with scrolled to selected date.

### ISSUE THREAD

**Issue by eugeniuszkeptia** [jonathantribouharet/JTCalendar#137]
Hi all, 
Is there a way to scroll week view calendar to a given date?

**Comment by jonathantribouharet** [comment]
Not with an animation, you can set the `currentDate` or call `loadPreviousPage` and `loadNextPage`. But there is no animation to go to a specific date.

**Comment by eugeniuszkeptia** [comment]
Great, set currentDate with currentDateSelected on the same date make it works.
Thanks.
