### ISSUE TITLE
UTC Date / selection of current date / today

### ISSUE THREAD

**Issue by Jules2010** [jonathantribouharet/JTCalendar#138]
I'm trying to select the first day of the month once the month page (next / previous) has changed.

I have a UTC date which is the first of the month, but the selection doesn't appear the filled red circle.
Also I'd expect if I clicked today that it showed that, instead of the blue filled circle.

My local time zone is British Summer Time, however I would expect that the date section obeys this and not UTC. I know that NSDate uses UTC, however I'm a little confused about the whole area. But my users could be in any time zone and I'd expect their current date or today to work with the red filled circle.

Here's my code.

![](http://i.stack.imgur.com/Rwf6k.png)

Thanks for your control and doing such a great job, I've almost got my solution working :)

**Comment by Jules2010** [comment]
I'd just like to confirm that...

http://stackoverflow.com/questions/30118968/how-to-get-actual-first-day-of-the-month-possible-with-my-time-zone?noredirect=1#comment48348080_30118968

**Comment by jonathantribouharet** [comment]
Don't use NSLog for read a date use a NSDateFormatter, it's a bug from iOS.

**Comment by Jules2010** [comment]
I wasn't in the code I have above, the setCurrentDate method never selects the the date passed in.
E.g. the first of the month date, never shows the 1st, it shows the 31st

**Comment by jonathantribouharet** [comment]
Xcode or NSLog use `description`method from the NSDate which have a bug with the timezone, add a NSDateFormatter a this point in the code and you will see there is no problem.
Believe me, you're not the first to fall in the trap.

**Comment by Jules2010** [comment]
I've tried to figure this out and had some help, but I can't get this to work. I have tried with the UTC time zone, which does produce the 1st of the month, but the date isn't selected on the calendar.

gregorian.timeZone = [NSTimeZone timeZoneWithName:@"UTC"];

Please can you provide any further assistance.

**Comment by Jules2010** [comment]
I've created a fork of your example, with the next / previous buttons, disabled swiping.. Which shows that setCurrentDate not working correctly. The red selection doesn't work here and when you tap today.

**Comment by Jules2010** [comment]
Here's my form url https://github.com/Jules2010/JTCalendar

**Comment by Jules2010** [comment]
Sorted :) Thanks :) see my fork
