### ISSUE TITLE
Select multiple dates

### ISSUE THREAD

**Issue by dylangyesbreghs** [jonathantribouharet/JTCalendar#139]
Is it possible to select multiple dates?

**Comment by thebirds** [comment]
Did you find the answer for this? 
I also need this feature but cannot find it.

**Comment by jonathantribouharet** [comment]
Did you open the example project?

**Comment by dylangyesbreghs** [comment]
I made my own implementation.
You can find it at https://github.com/dylangyesbreghs/JTCalendar/tree/develop-multiple-selection
