### ISSUE TITLE
Adding year to Month Display

### ISSUE THREAD

**Issue by JustK2** [jonathantribouharet/JTCalendar#145]
Hi Jonathan, 

Thank you so much for this calendar, it's been a great addition to our app! I am trying to have year display as well as Month and am having some trouble customizing/sizing. I added year to the month block component as there is no yearBlock property: 
    self.monthBlock = ^NSString *(NSDate *date, JTCalendar *jt_calendar){
        NSCalendar *calendar = jt_calendar.calendarAppearance.calendar;
        NSDateComponents *comps = [calendar components:NSCalendarUnitYear|NSCalendarUnitMonth fromDate:date];
        NSInteger currentMonthIndex = comps.month;

But I am getting a display like this:

![calendar052315](https://cloud.githubusercontent.com/assets/10579116/7784855/45abfd9e-012b-11e5-9bd3-b2450203fd28.png)

I need to be aligned and centered and still scrollable. Any help would be greatly appreciated. 

Kind regards, 
Karolyn

**Comment by jonathantribouharet** [comment]
Currently you can only display the year with the month, but the scroll is still on months, there is no block yearBlock because I didn't implement the feature. If you want have the year text below the month text, I did a hack in the example in monthBlock with:

    return [NSString stringWithFormat:@"%ld\n%@", year, month];
