### ISSUE TITLE
Lack ability to display number of weeks

### ISSUE THREAD

**Issue by huyta** [jonathantribouharet/JTCalendar#146]
It's better if support display week number.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

You can now.

**Comment by calvin** [comment]
I don't think the example project has a calendar that shows the week numbers.

**Comment by jonathantribouharet** [comment]
No the example don't show this but you can. By implementing

    - (void)calendar:(JTCalendarManager *)calendar prepareMenuItemView:(UIView *)menuItemView date:(NSDate *)date;

If you use the default implementation for menuItemView (I mean if you use the default view) implement:

    - (void)calendar:(JTCalendarManager *)calendar prepareMenuItemView:(UILabel *)menuItemView date:(NSDate *)date;


With this you can customize the label like you want and set the text you want.

The default implementation is:

    NSCalendar *calendar = _manager.dateHelper.calendar;
    NSDateComponents *comps = [calendar components:NSCalendarUnitYear|NSCalendarUnitMonth fromDate:date];
    NSInteger currentMonthIndex = comps.month;
    
    static NSDateFormatter *dateFormatter = nil;
    if(!dateFormatter){
        dateFormatter = [_manager.dateHelper createDateFormatter];
    }

    dateFormatter.timeZone = _manager.dateHelper.calendar.timeZone;
    dateFormatter.locale = _manager.dateHelper.calendar.locale;
    
    while(currentMonthIndex <= 0){
        currentMonthIndex += 12;
    }
    
    view.text = [[dateFormatter standaloneMonthSymbols][currentMonthIndex - 1] capitalizedString];
