### ISSUE TITLE
HI JT

### ISSUE THREAD

**Issue by DanielLe232** [jonathantribouharet/JTCalendar#149]
Thank you for this calendar!
I have the new issue. I want to user swipe in range year from 2014 to 2015.
I could modify what method?
Thank!

**Comment by jonathantribouharet** [comment]
For now you can't, but soon I will release a new version of the calendar, more customizable.

**Comment by DanielLe232** [comment]
Thank JT,
I hope new version have my feature :)

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
