### ISSUE TITLE
Simple way to control whether paging should occur (e.g. to block paging into the future)?

### ISSUE THREAD

**Issue by simonbromberg** [jonathantribouharet/JTCalendar#151]
Want to block ability to swipe into the future. Can block selection with canSelectDate, but what about canSwipe or max / min date like that?

Similar to https://github.com/jonathantribouharet/JTCalendar/issues/71 

Also doesn't seem to be a method to check what the current visible page (ie month) is. Guess I can keep track of it using an integer, updated when loadNextPage / loadPreviousPage is called, or when I change the current date.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
