### ISSUE TITLE
How do I reference a specific date ?

### ISSUE THREAD

**Issue by ghobs91** [jonathantribouharet/JTCalendar#155]
I want the table that I added to be updated based on which date in the calendar grid is selected. Right now, the method for when a date is selected looks like this:

    - (void)calendarDidDateSelected:(JTCalendar *)calendar date:(NSDate *)date
    {
        NSLog(@"Date: %@", date);
    }

Rather than just logging the date that was selected, I want to reference it like so:

    - (void)calendarDidDateSelected:(JTCalendar *)calendar date:(NSDate *)date
        {
            if (date = "July 29th") {
                // Reload table with respective July 29th events
            }
        }

The above is pseudocode for the task I want to complete, but I can't figure out how to reference the specific date selected ("July 29th") so that I can update the table accordingly. I can't seem to find any information in the documentation that describes the correct syntax to do this.

**Comment by jonathantribouharet** [comment]
This question is not directly related to my library but to your understanding of `NSDate`, I can only advise you to read the [documentation](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSDate_Class/index.html) or ask on [stackoverflow](http://stackoverflow.com/) the next time.

You just want to compare a `NSDate`, one way is to do:

	- (void)calendarDidDateSelected:(JTCalendar *)calendar date:(NSDate *)date
	{
		// NSDateFormatter is used to create a date from a string
		// static keyword is used to avoid create a new instance each time calendarDidDateSelected is called
	    static NSDateFormatter *dateFormatter = nil;
	    if(!dateFormatter){
	        dateFormatter = [NSDateFormatter new];
	        dateFormatter.dateFormat = @"yyyy-MM-dd"; // Read the documentation for dateFormat
	    }
	    
	    // The date you want to reference, 29 July 2015
	    // You may used static keyword depending of your case
	    NSDate *yourDateToCompare = [dateFormatter dateFromString:@"2015-07-29"]; 
	    if([yourDateToCompare compare:date] == NSOrderedSame){
	        
	    }
	}

However, using `NSDateFormatter` is a heavy operation (for the CPU) and I suppose you want to compare the date from a database so it will be better if you don't create `yourDateToCompare` in `calendarDidDateSelected` method but compare directly with the dates coming from your database (or whatever you use to store your data).
