### ISSUE TITLE
How to make months scroll vertically instead of horizontally?

### ISSUE THREAD

**Issue by ghobs91** [jonathantribouharet/JTCalendar#156]
In a previous issue with a similar problem you said to do this:

"Check to configureConstraintsForSubviews of JTCalendarContentView.m method and scrollViewDidScroll of JTCalendar.m, anywhere there are contentOffset used."

I'm having trouble understanding what you mean by this. What changes to contentOffset must be made in order for months to scroll vertically?

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
