### ISSUE TITLE
calendar initial start month is off by one month

### ISSUE THREAD

**Issue by jeffreyliu8** [jonathantribouharet/JTCalendar#157]
Hi, I tried to run this calendar sample code just fine, but I also tried to deploy this on a new project with swift, today is 7/1/2015, but when I run this calendar it always starts with August, I can't find the reason. I think the only place to set date is using [self.calendar setCurrentDate:[NSDate date]];    I am sure I didn't use it anywhere else. Now i am just hacking and when viewdidappear, i set the date to today to bypass this issue, but I don't think this is good.

**Comment by jonathantribouharet** [comment]
You may have to `[self.calendar reloadData];` in `viewDidAppear` or `viewWillAppear`.

**Comment by EmirTola** [comment]
I got the exact same bug in my Swift app. calling ```calendar.reloadData()``` in ```viewDidAppear``` doesn't look very nice apparently. 
For my app particularly I have an ```NSLayoutConstraint-IBOutlet``` and immediately after ```super.viewDidLoad()```I update the constant value of this constraint. Now I don't even need to reload my calendar in ```viewDidAppear```.
Hopefully this helps, still hacky, but might provide better user experience. :D

**Comment by Tommecpe** [comment]
Hello, thank you for the great work !

I have the same problem. Today is 7/10/2015, and my calendar is opening in August, event with [self.calendar reloadData]; in viewDidAppear or viewWillAppear.

setting the current date in view did load is not doing the trick for me...

```objective-c
- (void) viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self.calendar setCurrentDate:[NSDate date]];
    [self.calendar reloadData];
}
```

**Comment by doguhanokumus** [comment]
I have the same issue today

**Comment by jonathantribouharet** [comment]
Have you added?

	- (void)viewDidLayoutSubviews
	{
	    [self.calendar repositionViews];
	}

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

This bug should be gone.

**Comment by jeffreyliu8** [comment]
new one works great, thanks!
