### ISSUE TITLE
Different circle colour for specific date 

### ISSUE THREAD

**Issue by awomerjanjua** [jonathantribouharet/JTCalendar#159]
Currently if ```calendarHaveEvent``` returns YES the ```dayDotColor``` is set to indicate an event. 

I'm trying to make it so Instead of a dot its a circle indicating an event. 

That was easy as I just needed to change the size of the ```dotView``` in JTCalendarDayView.m ```configureConstraintsForSubviews```. 

But my issue is I still only have one instance of the ```dotView``` therefore only one colour for the indicator to play around with. 

Is there a way in ```calendarHaveEvent``` if the event is on a certain date set my ```dotView``` to colour1,  or if the event is on another date i specify set the ```dotView``` to colour2?

**Comment by jonathantribouharet** [comment]
No sorry, you currently cannot. This week I will release a new release fully customisable but it's a full rewrite of the current code.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
