### ISSUE TITLE
Any way to customize week day font?

### ISSUE THREAD

**Issue by ja6lee** [jonathantribouharet/JTCalendar#165]
With version 1.2.3 you could customize the font of the Week Days using calendarAppearance.weekDayTextFont, but it doesn't look like there is any replacement method for this in 2.0.0?

**Comment by jonathantribouharet** [comment]
Look in the Example project.
https://github.com/jonathantribouharet/JTCalendar/blob/master/Example/Example/CustomViewController.m

Line 145 the method `calendarBuildWeekDayView`.
