### ISSUE TITLE
I an using it in my project and  found there is some questions like bellow :

### ISSUE THREAD

**Issue by amesty** [jonathantribouharet/JTCalendar#167]
![1](https://cloud.githubusercontent.com/assets/12271716/8717221/e514a334-2bcb-11e5-8eab-d34de4a8fbf0.png)

hope you can help to solve it , thanks !

**Comment by jonathantribouharet** [comment]
You can you show me what locale and timeZone do you use with:
`    NSLog(@"%@ - %@", _calendarManager.dateHelper.calendar.timeZone, _calendarManager.dateHelper.calendar.locale.localeIdentifier);`

**Comment by jonathantribouharet** [comment]
I try tu reproduce your problem but I failed, can you tell me what locale, time zone, region you have setup?

**Comment by jonathantribouharet** [comment]
I found the bug, it's very stupid. I don't reinitialize `hidden` in `prepareDayView` just change the method:

	// Exemple of implementation of prepareDayView method
	// Used to customize the appearance of dayView
	- (void)calendar:(JTCalendarManager *)calendar prepareDayView:(JTCalendarDayView *)dayView
	{
	    dayView.hidden = NO; // <--- Add this line
	    
	    // Hide if from another month
	    if([dayView isFromAnotherMonth]){
	        dayView.hidden = YES;
	    }
