### ISSUE TITLE
Demo Project - update pods

### ISSUE THREAD

**Issue by AnthonyMDev** [jonathantribouharet/JTCalendar#170]
The `Podfile.lock`on the demo project is requiring `2.0.0` and the `Podfile` is attempting to install `2.0.2`. This is causing the `pod try` command to fail for your library.

Just a heads up!

Thanks

**Comment by jonathantribouharet** [comment]
Thank's, it's fixed.

**Comment by AnthonyMDev** [comment]
That was incredibly fast. Thank you!
