### ISSUE TITLE
Scrolling issue when using calendar control within navigation controller

### ISSUE THREAD

**Issue by johannwilfling** [jonathantribouharet/JTCalendar#179]
There are some weird vertical scrolling issues when using the calendar control within a navigation controller.
In one sample project the calendarMenuView can be scrolled vertically, in one other project with almost the same setup, the calendarContentView has a weird vertical scrolling.

Anyone noticed that?

**Comment by juanpaternina** [comment]
Hey. I think that happened to me. Just install the version 2.0.8 and I had this problem, then I go to version 1.1 and it worked well but needed to use some of the features of version 2.0.8, and when updating run correctly. Try to do it may work for you too.

**Comment by johannwilfling** [comment]
I also reverted back to 1.2 - but I leave this issue open for further tracking ..

**Comment by jonathantribouharet** [comment]
I fixed the problem, I have to do `_scrollView.contentInset = UIEdgeInsetsZero;`
Update your pod.
