### ISSUE TITLE
NOt able to integrate to my project

### ISSUE THREAD

**Issue by vikasgudi** [jonathantribouharet/JTCalendar#180]
I trying to Add JT calendar to my project, but am getting some error
"JTCalendar/JTCalendar.h"  file not found.

I have just added JTCalendar folder to my project. Do I need to fallow few more steps.

**Comment by jonathantribouharet** [comment]
There is no specific things with this library.

https://github.com/jonathantribouharet/JTCalendar#installation

I'm sorry but if you don't how to install a lib there is many tutorials on internet or site dedicated like stackoverflow.
