### ISSUE TITLE
is Installing cocoapods is nesessary to integrate your lib to any project ?

### ISSUE THREAD

**Issue by vikasgudi** [jonathantribouharet/JTCalendar#181]
Can I use your sdk without using cocoapods, I mean will it work if I just drag drop the JTCalendar folder.

**Comment by jonathantribouharet** [comment]
No, you can use this library without cocoapod, cocoapod is just a tool for simplify the installation and update of libraries.
If you just drag on drop the JTCalendar folder it works, but you need to choose "Create groups" and not "Create folder references".
It seems you don't know how import a library so I recommend you to use cocoapod, it's for your own good.
