### ISSUE TITLE
Week and month animation transition when switching

### ISSUE THREAD

**Issue by wodetian** [jonathantribouharet/JTCalendar#182]
hello，What plans do you have recently made a similar like this switch ，The effect is similar to  ![大姨吗](https://itunes.apple.com/cn/app/id527809600?ls=1&mt=8)

**Comment by jonathantribouharet** [comment]
The url for the image is wrong, it says "Not found".

**Comment by wodetian** [comment]
sorry，![Image of Yaktocat](http://i3.tietuku.com/56a284ec9dbe573f.gif)

**Comment by wodetian** [comment]
[美柚](https://itunes.apple.com/cn/app/id634896669?mt=8)

**Comment by jonathantribouharet** [comment]
I like the effect but I don't have the time yet to implement it. But I keep in mind.

**Comment by wodetian** [comment]
3Q~
