### ISSUE TITLE
First day missing with non-english locale

### ISSUE THREAD

**Issue by UnknownDude74** [jonathantribouharet/JTCalendar#183]
I've run into a problem while implementing your calendar control in a project that must support custom calendar locales. If the first day of the month is a saturday it doesn't show up on the horizontal calendar when using a custom locale (like "pt_PT") instead of the default english one ("en_US_POSIX"). The two screenshots that follow were taken from your example project:

If the english locale is used, it all works as expected:

```objective-c
[[_calendarManager.dateHelper calendar] setLocale:[NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"]];
```

![img_2342](https://cloud.githubusercontent.com/assets/6325243/9102025/bbbabb20-3be5-11e5-99f0-5a9d62d9a9ab.PNG)

However, if we switch it to the Portuguese locale:

```objective-c
[[_calendarManager.dateHelper calendar] setLocale:[NSLocale localeWithLocaleIdentifier:@"pt_PT"]];
```

![img_2341](https://cloud.githubusercontent.com/assets/6325243/9102024/b9d2c1ae-3be5-11e5-8588-bd73339a3e25.PNG)

**Comment by jonathantribouharet** [comment]
Duplicate with #172 and fixed.
