### ISSUE TITLE
Is it possible to get notified when a user scrolls left or right?

### ISSUE THREAD

**Issue by franciszabala** [jonathantribouharet/JTCalendar#185]
I tried using this

```
-(void) scrollViewWillBeginDragging:(UIScrollView *)scrollView 
```
But it looks like scrollView is being managed by scrollManager. I was wondering if there's an option to get notified. It doesn't have to be NSNotification. Just something that will let me know that the user has swiped.

**Comment by franciszabala** [comment]
Does setting my view as a delegate to JTHorizontalCalendarView safe?

**Comment by jonathantribouharet** [comment]
Yes you can use the scrollview delegate for `JTHorizontalCalendarView` and `JTVerticalCalendarView`.
But not for `JTCalendarMenuView`.

**Comment by pbassut** [comment]
Did you get the sorted? I need to implement this and I see no other way unless altering the internal API which I shouldn't do.

Could you provide a bit more steps?
