### ISSUE TITLE
Not able to Install JTCalendar as Files Couldn't Found

### ISSUE THREAD

**Issue by suryakantkachhi** [jonathantribouharet/JTCalendar#187]
Hi Guys,

as i am just a beginner in iOS apps development, i need a one 3rd party calendar tool to use it in my first app, and i found this JTCalendar (https://github.com/jonathantribouharet/JTCalendar) tool and tried so much but couldn't install it in my app as it is giving error              
that below files are not able to find due to some lacking which i am not able to catch.
#import "BasicViewController.h"
#import "CustomViewController.h"
#import "SelectionViewController.h"
#import "VerticalViewController.h"

as mentioned in this tool, i have added pods folder in app root directory and drag its xcodeproj file in to my app then added two target dependency 1) Pods and 2) Pods- JTCalendar then added linked lib also for the same .

pod file is also there but not sure if it not able to find the JTCalendar Directory.

Can some one please help me here or can share the full steps. it would be great help for me.

Thanks... :+1:

**Comment by juanpaternina** [comment]
Hi. SuryaKantkachhi.

In the next link are the steps for install and use the cocoapods. Don't try to add manually the libraries.
https://guides.cocoapods.org/using/using-cocoapods.html

Read and try to install JTCalendar again.

Regards.
