### ISSUE TITLE
 view the truncating days from weeks of the last and next month 

### ISSUE THREAD

**Issue by pola-mina** [jonathantribouharet/JTCalendar#188]
what is the setting or class responsible for this customisation (showing the days supposed to be located in the black box)
![untitled 2](https://cloud.githubusercontent.com/assets/13750432/9200991/5c5c3f92-4053-11e5-9eb2-ad2a269be172.png)

**Comment by jonathantribouharet** [comment]
In the example project:

	- (void)calendar:(JTCalendarManager *)calendar prepareDayView:(JTCalendarDayView *)dayView
	{
	    dayView.hidden = NO;

	    // Test if the dayView is from another month than the page
	    // Use only in month mode for indicate the day of the previous or next month
	    if([dayView isFromAnotherMonth]){ 
	        dayView.hidden = YES;
	    }
