### ISSUE TITLE
Method "focusSelectedDayChangeMode" is not longer avaliable.

### ISSUE THREAD

**Issue by juanpaternina** [jonathantribouharet/JTCalendar#189]
Hi, excellent work that they are doing with the library. I just wanted to ask you a question. How do I find the function "focusSelectedDayChangeMode"? in the new version 2.0.8. When I switch to the week view is not positioned in the week of the selected date.

Regards and thank you again.

**Comment by jonathantribouharet** [comment]
I don't understand what you mean by is the `focusSelectedDayChangeMode` function, never heard of it.
The selected date is not used when you change to the week mode anymore, but you can set the current date with `[_calendarManager setDate:yourDate];`

**Comment by interstateone** [comment]
I noticed this as well when migrating from 1.2.3 to the latest 2.x. I think this is what @juanpaternina was referring to: https://github.com/jonathantribouharet/JTCalendar/blob/1.2.3/JTCalendar/JTCalendarAppearance.h#L39

**Comment by juanpaternina** [comment]
I'm not working anymore in the project.. When i have in my hands again i will re-open. Thanks to all.
