### ISSUE TITLE
Fetch events into calendar

### ISSUE THREAD

**Issue by pistiolasm** [jonathantribouharet/JTCalendar#19]
Hi Jonathan, 
This calendar looks awesome. I am new in ios programming and I would to use this calendar in to my application. The only issue that I have is that I want to fetch some events from a website in to this calendar. Where/How can I do this?
Thank you.

**Comment by ayazkhaskheli** [comment]
i am new in ios your work is fantastic, i want to create events on selected date.. but unfortunately could not know how to do,, kindly help ..thanks and will remain ever thankful.
