### ISSUE TITLE
How to change week start day?

### ISSUE THREAD

**Issue by dev4dev** [jonathantribouharet/JTCalendar#192]
I need to change start day depending on Location (Monday|Sunday)

**Comment by jonathantribouharet** [comment]
Check the example project, you have to change the local of the calendar.

**Comment by dev4dev** [comment]
Yep, my bad, sorry. It works automatically. :+1:

**Comment by male87** [comment]
Also, you can do this in swift => 
calendarManager.dateHelper.calendar().firstWeekday = 1  (1 for Sunday, 2 for Monday, ...)
calendarManager.reload()
