### ISSUE TITLE
Change the text color of CalendarMenuView

### ISSUE THREAD

**Issue by udayasri** [jonathantribouharet/JTCalendar#194]
Hi ,

I want to change the text color of CalendarMenuView, ( Text color of the month ) . I tired both of the below codes .. But nothing worked. 

    _calendarMenuView.tintColor = [UIColor whiteColor];
    [_calendarMenuView setTintColor:(UIColor *) [UIColor whiteColor]];

Any idea how to fix this ?

**Comment by ilyon** [comment]
try this
self.calendar.calendarAppearance.menuMonthTextColor = [UIColor whiteColor];

**Comment by jonathantribouharet** [comment]
Sorry @ilyon your code is for 1.x version.
Now you have to implement `- (UIView *)calendarBuildMenuItemView:(JTCalendarManager *)calendar;`.
Example:

	- (UIView *)calendarBuildMenuItemView:(JTCalendarManager *)calendar;
	{
		UILabel *label = [UILabel new];
		label.textAlignment = NSTextAlignmentCenter;
	    label.textColor = [UIColor redColor];
	    
		return label;
	}

**Comment by udayasri** [comment]
Thanks a lot .. It works ..
