### ISSUE TITLE
Click on the current date is the day before

### ISSUE THREAD

**Issue by syyjay** [jonathantribouharet/JTCalendar#195]
when click the method - (void)calendar:(JTCalendarManager *)calendar didTouchDayView:(JTCalendarDayView *)dayView,the dayView.date is the day before.Is a bug?

**Comment by jonathantribouharet** [comment]
Nope is not a bug, use a NSDateFormater to read the date. This "bug" was reported a lot of time and it's not.

**Comment by syyjay** [comment]
I am user a NSDateFomater to read the date ,the date is right. Why use dayView.date  the date is the day before?Thank you .
