### ISSUE TITLE
Calendar vertical layout sometimes cut last week in month view

### ISSUE THREAD

**Issue by DrAma999** [jonathantribouharet/JTCalendar#196]
Hello, 
I write that bug as new issues.
In the sample Vertical Layout with the simulator in italian, Jenuary is cut as you can see from the screenshot.
![ios simulator screen shot 22 ago 2015 19 11 54](https://cloud.githubusercontent.com/assets/958522/9425030/2a914540-4902-11e5-9641-8fd1a2e71bfe.png)
![ios simulator screen shot 22 ago 2015 19 11 58](https://cloud.githubusercontent.com/assets/958522/9425031/2dae71f8-4902-11e5-8dfb-29c25efa0206.png)
It happens also with en_UK locale.

**Comment by jonathantribouharet** [comment]
Fixed. Thanks.
