### ISSUE TITLE
Converting back and forth from Week View to Month View

### ISSUE THREAD

**Issue by sajayshah** [jonathantribouharet/JTCalendar#197]
First of all, thanks for creating an awesome calendar framework.

Hopefully this video explains the issue I'm having:
http://gfycat.com/SpectacularDapperBlueandgoldmackaw

But anyways, say for example I'm in week view and I change to month view and select a date a week or more away from the current date selected. When I change back to week view, the week shown does not contain the date selected. Is there any way I can update the week view so it shows the week I selected when I was in month view?

**Comment by jonathantribouharet** [comment]
There is no sound on your video, but I think I understood what you want.
When you change the "view mode", you have to change the current date of the calendar, which is completely different from the date you have selected. You have to do something like:

```
    [_calendarManager setDate:_selectedDate];

    // And maybe do
    _calendarManager.settings.weekModeEnabled = YES;
    [_calendarManager reload];
````

**Comment by sajayshah** [comment]
Thanks! Your suggestions solved the problem!
