### ISSUE TITLE
Calendar view can not be scrolled when enable 2 pages

### ISSUE THREAD

**Issue by kylesunjk** [jonathantribouharet/JTCalendar#199]
Thanks for giving the good library for ios.
I have found out some issue when i start using it,

As I have defined there are only the current month and next month page enable in the delegate method, but somehow the page can not be scrolled from the current page to the next.

     _minDate = [_calendarManager.dateHelper addToDate:_todayDate months:0];
    
    _maxDate = [_calendarManager.dateHelper addToDate:_todayDate months:1];

But, it works fine when i enable 3 pages.

Can you help me found out whats the issue or give some suggestion how to handle my requirement.

**Comment by jonathantribouharet** [comment]
Thanks, it's fixed.
But it's highly probable there is the same bug with different configuration (when you have only 2 pages).

**Comment by kylesunjk** [comment]
Hi Jonathan

Thanks for your kindly help, it solve on my project.
