### ISSUE TITLE
On last update I can't set Monday as the first day of the week

### ISSUE THREAD

**Issue by pascualin** [jonathantribouharet/JTCalendar#201]
I use to call the following function to change the first day of the week on my calendar:

[self.calendar.calendarAppearance.calendar setFirstWeekday:2];

But after the update I can't find the way to do this. I was assuming it would be in the settings class, but doesn't seem to be there.

Thanks a lot for the component, I love it!

**Comment by jonathantribouharet** [comment]
Just check the Example projet or the readme https://github.com/jonathantribouharet/JTCalendar#internationalization--localization

    [_calendarManager.dateHelper.calendar setFirstWeekday:2]
