### ISSUE TITLE
Full three months view 

### ISSUE THREAD

**Issue by ashishpandita** [jonathantribouharet/JTCalendar#205]
Nice library thanks for your creative work. As I see this library creates three months left center and right but is there a way I can show three months completely. My requirement is to set a three month calendar view any help?  When a swipe is done it should load another full three months like wise.

**Comment by jonathantribouharet** [comment]
Currently no, but you could do it by subclassing or creating a new class for `JTHorizontalCalendarView` or by subclassing or creating a new class for `JTCalendarPageView` and returning a new instance in the method `- (UIView<JTCalendarPage> *)calendarBuildPageView:(JTCalendarManager *)calendar;`.

**Comment by ashishpandita** [comment]
Can you put up in detail, may be I did not get it. I need to dig this lib not sure from which corner should I start looks a whole bunch of stuff. Thanks.

**Comment by jonathantribouharet** [comment]
I'm not sure, but in theory I see 2 different ways:
- by subclassing or creating a new class of `JTHorizontalCalendarView`, you can build a system which display 3 `JTCalendarPageView` in the same time
- by subclassing or creating a new class of `JTCalendarPageView`, you can show more than one month in one page

I don't see how I can be more explicit. I can't code it for you, I don't have the time.

**Comment by ashishpandita** [comment]
I am using three instances of 
@property (weak, nonatomic) IBOutlet JTCalendarMenuView *calendarMenuViewA;
@property (weak, nonatomic) IBOutlet JTHorizontalCalendarView *calendarContentViewA;
@property (strong, nonatomic) JTCalendarManager *calendarManagerA;
//B
@property (weak, nonatomic) IBOutlet JTCalendarMenuView *calendarMenuViewB;
@property (weak, nonatomic) IBOutlet JTHorizontalCalendarView *calendarContentViewB;
@property (strong, nonatomic) JTCalendarManager *calendarManagerB;
//C
@property (weak, nonatomic) IBOutlet JTCalendarMenuView *calendarMenuViewC;
@property (weak, nonatomic) IBOutlet JTHorizontalCalendarView *calendarContentViewC;
@property (strong, nonatomic) JTCalendarManager *calendarManagerC;

And in all delegates I am checking the instances 

// Used to limit the date for the calendar, optional
- (BOOL)calendar:(JTCalendarManager *)calendar canDisplayPageWithDate:(NSDate *)date
{
    if ([calendar isEqual:self.calendarManagerA]) {
       
        _minDate = [calendar.dateHelper addToDate:_calanderDateA months:0];
        _maxDate = [calendar.dateHelper addToDate:_calanderDateA months:0];
        
    }else if ([calendar isEqual:self.calendarManagerB]){
       
        _minDate = [calendar.dateHelper addToDate:_calanderDateB months:0];
        _maxDate = [calendar.dateHelper addToDate:_calanderDateB months:0];
        
    }else if ([calendar isEqual:self.calendarManagerC])
    {
        _minDate = [calendar.dateHelper addToDate:_calanderDateC months:0];
        _maxDate = [calendar.dateHelper addToDate:_calanderDateC months:0];
    }
    
    return [calendar.dateHelper date:date isEqualOrAfter:_minDate andEqualOrBefore:_maxDate];
}

similarly other delegates, 
my requirement was to add multiple dots so I have added collection view  to hold array of dots
here is my code for multiple dots where I have added collectionView Class in to JTCalendarDayView
//
//  JTCalendarDayView.h
//  JTCalendar
//
//  Created by Jonathan Tribouharet
//

#import <UIKit/UIKit.h>

#import "JTCalendarDay.h"
#import "JTCollectionView.h"
//Ashish//
static NSString *CollectionViewCellIdentifier = @"CollectionViewCellIdentifier";

@interface JTCalendarDayView : UIView<JTCalendarDay>

@property (nonatomic, weak) JTCalendarManager *manager;

@property (nonatomic) NSDate *date;

@property (nonatomic, readonly) UIView *circleView;
@property (nonatomic, readonly) UIView *dotView;
@property (nonatomic, readonly) UILabel *textLabel;

@property (nonatomic) CGFloat circleRatio;
@property (nonatomic) CGFloat dotRatio;

@property (nonatomic) BOOL isFromAnotherMonth;

/*!
 * Must be call if override the class
 */
- (void)commonInit;
//Ashish//
@property (nonatomic, strong) JTCollectionView *collectionView;
- (void)setCollectionViewDataSourceDelegate:(id<UICollectionViewDataSource, UICollectionViewDelegate>)dataSourceDelegate indexPath:(NSIndexPath *)indexPath dataSource:(NSMutableArray*)dataSource;
@end

here is the m file
//
//  JTCalendarDayView.m
//  JTCalendar
//
//  Created by Jonathan Tribouharet
//

#import "JTCalendarDayView.h"

#import "JTCalendarManager.h"

@implementation JTCalendarDayView

- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if(!self){
        return nil;
    }
    
    [self commonInit];
    
    return self;
}

- (instancetype)initWithCoder:(NSCoder *)aDecoder
{
    self = [super initWithCoder:aDecoder];
    if(!self){
        return nil;
    }
    
    [self commonInit];
    
    return self;
}

- (void)commonInit
{
    //Ashish//
    UICollectionViewFlowLayout *layout = [[UICollectionViewFlowLayout alloc] init];
    layout.sectionInset = UIEdgeInsetsMake(3, 3, 3, 3);
    layout.itemSize = CGSizeMake(6, 6);
    layout.scrollDirection = UICollectionViewScrollDirectionHorizontal;
    
    self.collectionView = [[JTCollectionView alloc] initWithFrame:CGRectZero collectionViewLayout:layout];
    [self.collectionView registerClass:[UICollectionViewCell class] forCellWithReuseIdentifier:CollectionViewCellIdentifier];
    self.collectionView.backgroundColor = [UIColor clearColor];
    self.collectionView.showsHorizontalScrollIndicator = NO;
    self.collectionView.dataSourceArray = [NSMutableArray new];
    [self addSubview:self.collectionView];
    //
    self.clipsToBounds = YES;
    
    _circleRatio = 1.0;
    _dotRatio = 1. / 9.;
    
    {
        _circleView = [UIView new];
        [self insertSubview:_circleView belowSubview:self.collectionView];
        
        _circleView.backgroundColor = [UIColor colorWithRed:0x33/256. green:0xB3/256. blue:0xEC/256. alpha:.5];
        _circleView.hidden = YES;
        
        _circleView.layer.rasterizationScale = [UIScreen mainScreen].scale;
        _circleView.layer.shouldRasterize = YES;
    }
    
    {
        _dotView = [UIView new];
        [self addSubview:_dotView];
        
        _dotView.backgroundColor = [UIColor redColor];
        _dotView.hidden = YES;
        
        _dotView.layer.rasterizationScale = [UIScreen mainScreen].scale;
        _dotView.layer.shouldRasterize = YES;
        
        
    }
    
    {
        _textLabel = [UILabel new];
        [self addSubview:_textLabel];
        
        _textLabel.textColor = [UIColor blackColor];
        _textLabel.textAlignment = NSTextAlignmentCenter;
        _textLabel.font = [UIFont systemFontOfSize:[UIFont systemFontSize]];
    }
    
    {
        UITapGestureRecognizer *gesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(didTouch)];
        
        self.userInteractionEnabled = YES;
        [self addGestureRecognizer:gesture];
    }
}

- (void)layoutSubviews
{
    _textLabel.frame = self.bounds;
    
    CGFloat sizeCircle = MIN(self.frame.size.width, self.frame.size.height);
    CGFloat sizeDot = sizeCircle;
    
    sizeCircle = sizeCircle * _circleRatio;
    sizeDot = sizeDot * _dotRatio;
    
    sizeCircle = roundf(sizeCircle);
    sizeDot = roundf(sizeDot);
    
    _circleView.frame = CGRectMake(0, 0, sizeCircle, sizeCircle);
    _circleView.center = CGPointMake(self.frame.size.width / 2., self.frame.size.height / 2.);
    _circleView.layer.cornerRadius = 0.0;  //sizeCircle / 2.;
    
    _dotView.frame = CGRectMake(0, 0, sizeDot, sizeDot);
    _dotView.center = CGPointMake(self.frame.size.width / 2., (self.frame.size.height / 2.) +sizeDot * 2.5);
    _dotView.layer.cornerRadius = sizeDot / 2.;
    //Ashish//
    self.collectionView.frame =  CGRectMake(6, (self.frame.size.height / 2.) +sizeDot*2.5, self.frame.size.width-12,6);
}

- (void)setDate:(NSDate *)date
{
    NSAssert(date != nil, @"date cannot be nil");
    NSAssert(_manager != nil, @"manager cannot be nil");
    
    self->_date = date;
    [self reload];
}

- (void)reload
{
    static NSDateFormatter *dateFormatter = nil;
    if(!dateFormatter){
        dateFormatter = [_manager.dateHelper createDateFormatter];
        [dateFormatter setDateFormat:@"dd"];
    }
    
    _textLabel.text = [dateFormatter stringFromDate:_date];
    
    [_manager.delegateManager prepareDayView:self];
}

- (void)didTouch
{
    [_manager.delegateManager didTouchDayView:self];
}
//Ashish//
- (void)setCollectionViewDataSourceDelegate:(id<UICollectionViewDataSource, UICollectionViewDelegate>)dataSourceDelegate indexPath:(NSIndexPath *)indexPath dataSource:(NSMutableArray*)dataSource
{
    self.collectionView.dataSource = dataSourceDelegate;
    self.collectionView.delegate = dataSourceDelegate;
    self.collectionView.dataSourceArray = dataSource;
    self.collectionView.indexPath = indexPath;
    [self.collectionView reloadData];
}

@end
It can be helpful to some one. 
<img width="764" alt="screen shot 2015-09-20 at 6 27 14 pm" src="https://cloud.githubusercontent.com/assets/188247/9980862/535522e6-5fc6-11e5-8738-052b4508d29e.png">
If you can give any more suggestions that should be nice. 

Thanks, 
Ashish
