### ISSUE TITLE
How to select and deselect date with out user touch?

### ISSUE THREAD

**Issue by ashishpandita** [jonathantribouharet/JTCalendar#208]
Is there any method which I can use to select or deselect dates that should not reload every thing again.

**Comment by ashishpandita** [comment]
I found this in JTCalendarManager.h
- (void)reload
{
    [_contentView setDate:_contentView.date];
}

**Comment by jonathantribouharet** [comment]
There is no selection system in the calendar, I removed it from the calendar because it's too specific to your usage. But I provided an example of selection in the example project.

**Comment by ashishpandita** [comment]
Can you please mention which version I have to look for the example.
