### ISSUE TITLE
Disable load of pervious months 

### ISSUE THREAD

**Issue by jaycdave88** [jonathantribouharet/JTCalendar#211]
I do not want the user to be able to scroll to the pervious months - just the current and/or future months. 

Current behavior:
- A User can view pervious as well as future months

Expected behavior:
- A User can only view current month with future months

**Comment by jonathantribouharet** [comment]
You didn't read the README or test the example project: https://github.com/jonathantribouharet/JTCalendar#questions

You just have to implement `canDisplayPageWithDate` method.
https://github.com/jonathantribouharet/JTCalendar#pagination
