### ISSUE TITLE
Last week of some months is hidden for vertical calendar

### ISSUE THREAD

**Issue by dylanslewis** [jonathantribouharet/JTCalendar#212]
The last row of dates doesn't show for December 2015.

This only affects devices, and appears completely fine on the Simulator.

![img_1394](https://cloud.githubusercontent.com/assets/8267782/10137168/1ee781b8-65f0-11e5-8799-2a3f520ffac6.jpg)

**Comment by Albarian** [comment]
I have found the same problem but on simulator too.

**Comment by nguyenvuphongit** [comment]
Me too. I got this issue when I try set _calendarManager.settings.pageViewNumberOfWeeks = 0; // Automatic number of weeks.

**Comment by mciarlo** [comment]
Same issue here.

**Comment by johnvuko** [comment]
Sorry guys, I don't maintain this projet anymore.
I merge #391 and release a new version 2.2.6.
I didn't test the PR.
