### ISSUE TITLE
change the color of the name of the month in week mode

### ISSUE THREAD

**Issue by AladinWay** [jonathantribouharet/JTCalendar#217]
i want to change the color of the text of the month and also make the circle of the selected day bigger

![img](https://cloud.githubusercontent.com/assets/12564483/10549682/7328a02e-743a-11e5-98f7-9476c9c4981d.PNG)

**Comment by Jaikant** [comment]
I would like to customise the color of the text of the month, looked through the JTCalendarMenuView but couldn't figure out how to do it. Any tips?

**Comment by jonathantribouharet** [comment]
For the menu view one of the two methods:

```
- (UIView *)buildMenuItemView;
- (void)prepareMenuItemView:(UIView *)menuItemView date:(NSDate *)date;
```

For the day view
```
- (void)prepareDayView:(JTCalendarDayView*)dayView;
```

**Comment by Jaikant** [comment]
Hey thanks for the reply, but which property for the menuItemView would modify the text color?

**Comment by jonathantribouharet** [comment]
`menuItemView` is just a UILabel so use `textColor` property. It's a `UIView` in the delegate for letting other people override this.
