### ISSUE TITLE
Adding event details view 

### ISSUE THREAD

**Issue by v1shnu-mee** [jonathantribouharet/JTCalendar#222]
Hi , I would like to add event details for a particular date when user switches to week view.
There is a considerable amount of space below the week view as i am using only one week to display at a time.I would add a view below the the dates so that it looks like it is part of JTHorizontalCalendarView. Can you tell me where and how i can do that.

**Comment by jonathantribouharet** [comment]
The view with event details are very specific to your design and the informations about the event, there is no common view for that.
This view is below JTCalendarHorizontalView so it's not part of this library.
You have to create your own view.
