### ISSUE TITLE
customise week day text capitalisation in calendarBuildWeekDayView

### ISSUE THREAD

**Issue by omerozk** [jonathantribouharet/JTCalendar#223]
Week day label text is shown only in "uppercaseString" i need to change it to “capitalised"
JTCalendarWeekDayView.h line 81 -> [day uppercaseString]

Do you have an idea how can i change that.

Thanks

**Comment by jonathantribouharet** [comment]
You could implement your own `calendarBuildWeekDayView` method and return an `UIView` which implement `JTCalendarWeekDay`.
