### ISSUE TITLE
Thanks for this lib，how to set firstWeekday in this version？

### ISSUE THREAD

**Issue by mxpasser** [jonathantribouharet/JTCalendar#228]
in the old version，we can set 'firstWeekday' like this: "...calendar.firstWeekday = 1,2...",but in this version,  the 'firstWeekday' property went away. when the 'firstWeekday' come back ? and how to set 'firstWeekday' in the new version! ^_^ thank you！

**Comment by jonathantribouharet** [comment]
Do you use `self.calendar.calendarAppearance.calendar.firstWeekday = 1`?
Because I don't have the problem. I think (try to remember) it may have a problem when you set the `locale` and the `firstWeekday` for `NSCalendar`, the `locale` override `firstWeekday`.

**Comment by mxpasser** [comment]
thank you for your reply !
i use the new version,and solve the problem about firstWeekday setting. 
i tried this:
"_calendarManager.dateHelper.calendar.locale = [NSLocale localeWithLocaleIdentifier:@"zh_CN"];
    _calendarManager.dateHelper.calendar.firstWeekday = 2;"
it works！
---------------------------------------------------separator-----------------------------------------------
Another question:
how to disable the year menu and weekday menu scrolling? 
![image](https://cloud.githubusercontent.com/assets/3272620/12045897/8895b40a-aee7-11e5-9657-a524e7dfb1dd.png)

thanks a lot , have a good day! ^_^
