### ISSUE TITLE
How can I go to a specific date by programming?

### ISSUE THREAD

**Issue by huutrung789** [jonathantribouharet/JTCalendar#233]
I have a question, I want to go to a specific date, So How can I do that by programming?
I read source code, but have no delegate or function.
Can you help me do this?
Thanks and Best Regards.

**Comment by jonathantribouharet** [comment]
Just do `[_calendarManager setDate:[NSDate date]];`

**Comment by sjuvvalapalem** [comment]
@huutrung789  Were you able to get this working.. please look at the issue 381 opened by me,

For some reason no matter what i set the date to its always selecting todays date.

https://github.com/jonathantribouharet/JTCalendar/issues/381

Any help on this is greatly appreciated.
