### ISSUE TITLE
how to disable future dates

### ISSUE THREAD

**Issue by patriksharma** [jonathantribouharet/JTCalendar#234]
hello,

I need to know in case i want to disable all future dates in calendar , how i will do that ?

in date picker we have setmaximumdate or setminimum date feature.

**Comment by LeeJunhui** [comment]
`- (BOOL)calendar:(JTCalendarManager *)calendar canDisplayPageWithDate:(NSDate *)date
{
    return [_calendarManager.dateHelper date:date isEqualOrAfter:minDate andEqualOrBefore:endDate];
}`
