### ISSUE TITLE
I think  your demo is so great,but i need change the order of weekMenu.

### ISSUE THREAD

**Issue by quchangle** [jonathantribouharet/JTCalendar#236]
thank you for your demo,it's useful for me. but i need little change for its weekMenu with"mon tues wed thur fri satur sun". could you give some  tips. thank you for advance!!! 
![default](https://cloud.githubusercontent.com/assets/15903587/12507525/44dac460-c131-11e5-9a41-491960289bb4.png)

**Comment by LeeJunhui** [comment]
I have the same issue, and I can't figure out how to reorder the week view.

**Comment by quchangle** [comment]
Do you have any good ideas? I have tried so many way while I cannot solve it .

**Comment by LeeJunhui** [comment]
You literally need to a single line to solve that.
`_calendarManager.dateHelper.calendar.firstWeekday = 2;`
The `firstWeekday` property can help you~
![img](http://ww1.sinaimg.cn/large/c0644dbegw1f0biopntarj20af0ijq39.jpg)

**Comment by quchangle** [comment]
so great!  thank you for your help.～～!
