### ISSUE TITLE
Great Lib but Always return privious date in didTouchDayView delegate method.

### ISSUE THREAD

**Issue by LathigaraBhavesh** [jonathantribouharet/JTCalendar#238]
Hi,
Great Lib will you please tell how can I fix this issue
always return previous date.
![screen shot 2016-01-26 at 5 00 27 pm](https://cloud.githubusercontent.com/assets/10243442/12579496/60206886-c44e-11e5-8194-fb0783aa3c8e.png)

**Comment by jonathantribouharet** [comment]
Don't use `NSLog` to print date use a `NSDateFormatter`, `NSLog`doesn't take care of the timezone.

```objective-c
NSDateFormatter *dateFormatter = [_calendarManager.dateHelper createDateFormatter];
dateFormatter.dateFormat = @"yyyy'-'MM'-'dd' 'HH':'mm':'ss";
NSLog(@"%@", [dateFormatter stringFromDate:yourDate]);
```
