### ISSUE TITLE
Change date selected to the first of the month when user loads new month.

### ISSUE THREAD

**Issue by sajayshah** [jonathantribouharet/JTCalendar#242]
http://gfycat.com/UnselfishSmugAcornwoodpecker

The link above shows that for the current in month view, the calendar does not update the date when the user scrolls pages. Ideally when months are scrolled, the first of the new month shown should be highlighted. With week view, the first day of the new week should be highlighted. 

In - (void)calendar:(JTCalendarManager *)calendar prepareDayView:(JTCalendarDayView *)dayView, I've tried to find the dayView with the date that corresponds to the dayView of first of the previous month, current month, and next month, and then whether - (void)calendarDidLoadNextPage:(JTCalendarManager *)calendar or - (void)calendarDidLoadPreviousPage:(JTCalendarManager *)calendar page is called, I would 'tap' that day using - (void)calendar:(JTCalendarManager *)calendar didTouchDayView:(JTCalendarDayView *)dayView in the calendarDidLoadNext/PreviousPage methods. However this is causing some serious view issues, so I was wondering if you knew of a better way to accomplish what I'm trying to do.

Thanks.

**Comment by judemorrissey** [comment]
Have you tried implementing the `JTCalendarDelegate` methods below? These look like the proper methods for setting the dateSelected to the first of the new month
```
/*!
 * Indicate the previous page became the current page.
 */
- (void)calendarDidLoadPreviousPage:(JTCalendarManager *)calendar;

/*!
 * Indicate the next page became the current page.
 */
- (void)calendarDidLoadNextPage:(JTCalendarManager *)calendar;
```
