### ISSUE TITLE
didTouchDayView not gives the today date

### ISSUE THREAD

**Issue by mohshinshah1903** [jonathantribouharet/JTCalendar#260]
When i click on today date below method get called.
- (void)calendar:(JTCalendarManager *)calendar didTouchDayView:(JTCalendarDayView *)dayView  

But dayView.date := gives me prevous date and not todays date.

for eg : if today is : 20/04/2016
dayview.data shows : 19/04/2016

Please help

**Comment by Janrin** [comment]
please use NSDateFormatter with your timezone to format your touched date, it will return the right date string.

**Comment by zeeshansshaikh** [comment]
@Janrin 

hey buddy would you please tell me how can i change the time format actually i am bit new , from where i can change the thing ? here is my code 

// Used only to have a key for _eventsByDate
- (NSDateFormatter *)dateFormatter
{

    
    static NSDateFormatter *dateFormatter;
    if(!dateFormatter){
        dateFormatter = [NSDateFormatter new];
       [dateFormatter setDateFormat:@"yyyy-MM-dd HH:mm:ss"];
       [dateFormatter setTimeZone:[NSTimeZone timeZoneWithName:@"GMT"]];
  }
  return dateFormatter;
}
