### ISSUE TITLE
how to make monday show in the first column

### ISSUE THREAD

**Issue by himyfairy** [jonathantribouharet/JTCalendar#266]
By default, the first column is sunday and the second column is monday, I wonder if there is a way to make the first column monday?

**Comment by himyfairy** [comment]
I have figured it out, which day comes the first column follows iPhone's system default configuration. For example, in China or USA, iPhone's system calendar app shows Sunday at the first column, but in UK, the first column is Monday, so if I want JTCalendar to show Monday at the first column, I'll need to go to "Settings -> General -> Language&Region -> Region", change to "United Kingdom", after this, JTCalendar will show Monday at the first column. (PS:it will be extremely nice if a method is provided to customize  which day to show at the first column, just as iPhone's system calendar app does:"Settings -> Mail, Contacts, Calendar -> Start Week On") :)

**Comment by jonathantribouharet** [comment]
Hi, JTCalendar use `NSCalendar` which define what's the first day of the week, either by defining a locale or by setting directly the first day of the week in the `calendar` variable.

https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSCalendar_Class/

By the way if you had check the Example project, you would see it.
https://github.com/jonathantribouharet/JTCalendar/blob/master/Example/Example/CustomViewController.m#L44

**Comment by himyfairy** [comment]
oops, how could I miss that. It's so nice of you to tell me and have a nice day! :)
