### ISSUE TITLE
Cannot Select "Trailing" Day in Compact View

### ISSUE THREAD

**Issue by judemorrissey** [jonathantribouharet/JTCalendar#274]
![bug](https://cloud.githubusercontent.com/assets/5974771/16397179/a884f2a8-3c77-11e6-982b-abb86149eda2.gif)
Please see attached gif of issue. Say for the last week of the month of June 2016, there are 3 "trailing" days in July. Selecting one of those July days in compact view causes the calendar to advance to the first *full* week of July, effectively being unable to select the trailing day itself.

This is observed in the example calendar code, reporting as a bug.

**Comment by jonathantribouharet** [comment]
The problem come from my implementation in the example code (so no need to update anything).
The solution is to just disable the scroll in weekMode because there is no reason to change the page in weekMode. I commit a fix in the example project.

By the way, thank you for helping on others issues.

**Comment by judemorrissey** [comment]
Thanks for clarifying, and you're welcome! I try to give back from what I take from
