### ISSUE TITLE
How to change JTCalender's firstDay at weekMode

### ISSUE THREAD

**Issue by chuckern** [jonathantribouharet/JTCalendar#277]
I use JTCalender in my project. I change the mode to week mode and set the maxDate as today with [NSDate date], and set the minDate as the day one week before, but the first day is still Sunday not the minDate's weekday, and the maxday still is the Saturday, not the current day.

**Comment by jonathantribouharet** [comment]
You misunderstand the minDate and the `firstWeekDay` property of `NSCalendar` which can be set directly or you can set a locale (which is better for internationalization).

`_calendarManager.dateHelper.calendar.locale = [NSLocale localeWithLocaleIdentifier:@"fr_FR"];`

**Comment by chuckern** [comment]
Solved.THX for your help. And sorry for the bother.
I am in trouble with this for a longtime...
