### ISSUE TITLE
Add two labels on left and right of menu view as shown in second screenshot.

### ISSUE THREAD

**Issue by RahuliOSDev** [jonathantribouharet/JTCalendar#280]

**Comment by gowtham318** [comment]
u got the answer for it ?

**Comment by gowtham318** [comment]
plese guide me that how to add two labels as shown in second screenShot

**Comment by jonathantribouharet** [comment]
By changing `contentRatio` of  `_calendarMenuView`:
`_calendarMenuView.contentRatio = .5;`
