### ISSUE TITLE
Add support for custom day format in JTCalendarDayView

### ISSUE THREAD

**Issue by sguillope** [jonathantribouharet/JTCalendar#283]
[`JTCalendarDayView:122`](https://github.com/jonathantribouharet/JTCalendar/blob/2.1.7/JTCalendar/Views/JTCalendarDayView.m#L122) uses a hard-coded day format of `"dd"` to display the days of the months in the calendar.

It would be nice if this format could be customized. For example we would like to be able to use `"d"` instead (no leading `0` for single digit days).

The simplest thing I can think of is to introduce a property on [`JTCalendarDay`](https://github.com/jonathantribouharet/JTCalendar/blob/2.1.7/JTCalendar/Protocols/JTCalendarDay.h) to be able to set the day format through [`[JTCalendarDelegate calendar:prepareDayView:]`](https://github.com/jonathantribouharet/JTCalendar/blob/2.1.7/JTCalendar/JTCalendarDelegate.h#L108). The property could be a `BOOL` indicating if the day should be padded with `0` (default).

**Comment by jonathantribouharet** [comment]
I just expose the dateFormatter of JTCalendarDayView, you just have to update the pod.
