### ISSUE TITLE
prepareMenuItemView is called with date = null

### ISSUE THREAD

**Issue by anutripa** [jonathantribouharet/JTCalendar#286]
We are seeing this issue sometimes where prepareMenuItemView gets called with date = null. Is it expected? What are the scenarios when we will have date = null?

**Comment by jonathantribouharet** [comment]
When you have implemented `canDisplayPageWithDate` for having a limited set of months, the month before the minimum date and the month after the maximum date maybe displayed but not accessible (I'm not 100% sure the test is simple).
The scroll doesn't let the user go in the month off limit but he can see it with the bounce of the scroll.
You may want to have a specific design for this months.
Or you may just ignore it.
