### ISSUE TITLE
How to create event with NSDate

### ISSUE THREAD

**Issue by SwiftySrl** [jonathantribouharet/JTCalendar#29]
Hi developer;  
I'm a developer as well, and I'm trying to implement inside JTCalendar some event taken from NsDate*dateSelected

In it I've some date in "dd/MM/yyyy HH:mm":

NSLog(@"%@",dateselected)
 "2014-12-09 00:05:41.908 Database Demo[1348:31927] 2014-12-09 09:39:37 +0000
2014-12-09 00:05:41.911 Database Demo[1348:31927] 2014-12-14 09:32:26 +0000
2014-12-09 00:05:41.913 Database Demo[1348:31927] 2014-12-20 08:08:09 +0000"

When I try to implement the date of "dateSelected" in the eventsByDate[key], it makes  just one event (the last one that I've insert in the dateSelected).

Here the code:
- (void)createEvents
  {
      eventsByDate = [NSMutableDictionary new];
  
  ```
  NSDate *myDate = dateSelected;
  
  NSString *key = [[self dateFormatter] stringFromDate:myDate];
  
  if(!eventsByDate[key]){
      eventsByDate[key] = [NSMutableArray new];
  }
  
  [eventsByDate[key] addObject:myDate];
  }
  ```
  
  }

Can you help me ???

Have a nice day......;)

**Comment by artemkalinovsky** [comment]
I've checked out how to do this!
