### ISSUE TITLE
Getting dayView frame (0, 0, 0, 0) from prepareDayView.

### ISSUE THREAD

**Issue by ikousik** [jonathantribouharet/JTCalendar#291]
I want to add a circular of half circular layer on top of the JTCalendarDayView. I am trying to make a UIBezierPath from the dayView frame. The dayView frame is coming (0, 0, 0, 0)  for the first time. If I change the month it's coming properly. How to get it done?

**Comment by jonathantribouharet** [comment]
Unfortunately, the only way to do that and keeping good performance is by creating your own class which inherits from `JTCalendarDayView`.
