### ISSUE TITLE
Struggling with a way to get current month/week on screen.

### ISSUE THREAD

**Issue by roadst3r** [jonathantribouharet/JTCalendar#292]
I've been trying to get the current month from JTCalendar manager without any success.
Its easy when the user touches a day, but I want to update my own label, when user swipes the month.
There are 2 methods: calendarDidLoadNextPage & calendarDidLoadPreviousPage, that are triggered when user swipe the month or week, but after that, I cant get the month date from anywhere, visible month date, not selected one.

Any ideas?

**Comment by jneiluj** [comment]
Use date from calendar.date in the 2 delegates (or calendarManager.date) and not dateSelected saved in - (void)calendar:(JTCalendarManager *)calendar didTouchDayView:(JTCalendarDayView *)dayView;

**Comment by jonathantribouharet** [comment]
Just like that `[_calendarManager date];`

**Comment by brunotereso-acceptto** [comment]
I don't have the code with me right now, but from what I remember [_calendarManager date] was updated after choosing a day.
My problem was getting the month while swiping the calendar without choosing any day.

**Comment by roadst3r** [comment]
I don't have the code with me right now, but from what I remember [_calendarManager date] was updated after choosing a day.
My problem was getting the month while swiping the calendar without choosing any day.

**Comment by jonathantribouharet** [comment]
The manager is just a proxy for the date in `JTHorizontalCalendarView` which is updated in continuous during the scroll. Check again and come back if you still have the problem.
