### ISSUE TITLE
Number of Days per week 

### ISSUE THREAD

**Issue by bhargavbajani** [jonathantribouharet/JTCalendar#298]
i want to customise  number of days per week . i set to  6 day show per week but when i scroll  day is missing . calendar week star from sunday so every saturday miss in display. 
![simulator screen shot 26-sep-2016 2 48 12 pm](https://cloud.githubusercontent.com/assets/13344552/18829070/48001bd8-83f8-11e6-86e8-dbe52d4be262.png)

so how to achieve that scenario?

want to set dynamic number of days show in week .

**Comment by jonathantribouharet** [comment]
I didn't expect someone to try to customize the number of days per week.
You have to implement your own `JTCalendarWeekView` in my Obj-C implementation you have a `NUMBER_OF_DAY_BY_WEEK` variable, I think just by changing this value you may achieve what you want.

With this technique you will have the same problem with the scroll.
So you also have to implement `JTCalendarPageView` and change the line 112
```
weekDate = [_manager.dateHelper addToDate:weekDate weeks:1];
by
weekDate = [_manager.dateHelper addToDate:weekDate days:6];
```

And finally, in your controller (or whatever implement `JTCalendarDelegate`) implement `dateForPreviousPageWithCurrentDate` and `dateForNextPageWithCurrentDate` which by default add / remove 1 week or 1 month.

Good luck.

**Comment by bhargavbajani** [comment]
hi, thank you for solution 

Applied both changes in files and did One more change in file "JTCalendarPageView" . replace  

weekDate = [_manager.dateHelper firstWeekDayOfWeek:_date]; 
by
weekDate = _date;
