### ISSUE TITLE
Need to show year in menuView

### ISSUE THREAD

**Issue by neetin** [jonathantribouharet/JTCalendar#299]
In previous version it shows year in calendar header like this September, 2016.
Now the is no property to set / show year in menuView. 
Is there any API/function for this? If not, we need to add this feature.

Thanks!

**Comment by panyaspy** [comment]
@neetin  +1 i need to

**Comment by panyaspy** [comment]
@neetin  hi i fixed this issue via swift language. do you want to get it ?

**Comment by jonathantribouharet** [comment]
If only you have check the example project:

https://github.com/jonathantribouharet/JTCalendar/blob/bcd3712ad1ddedb769262653857f34fa533fe37e/Example/Example/CustomViewController.m#L136

**Comment by panyaspy** [comment]
@jonathantribouharet  thank you! that's it 👍
