### ISSUE TITLE
Can not set firstWeekDay 

### ISSUE THREAD

**Issue by colditz18** [jonathantribouharet/JTCalendar#306]
Using JTCalendar (2.1.9) in iOS 10 I can not set firstWeekDay and timeZone. When trying to set it with

```
    calendarManager.dateHelper.calendar.firstWeekday = 2
```

It gives me an error saying Method calendar was used as a property; add() to call it, and using the fix xcode offers, I get this

```
    calendarManager.dateHelper.calendar().firstWeekday = 2
```

And the error "Cannot" assign to property: function call returns immutable value

**Comment by kishykumar** [comment]
Hitting the same issue. Did anyone find the solution?

**Comment by kishykumar** [comment]
Found it! Rewriting it as the following works: 
==
        var calendar = self.calendarManager.dateHelper.calendar()
        calendar.firstWeekday = 4 // Wednesday
==

**Comment by kishykumar** [comment]
@jonathantribouharet  It's not working now. I am not sure how it worked before with the answer that I gave before. Can you please help here/ reopen the bug?

**Comment by kishykumar** [comment]
@colditz18 Did you figure out this bug?
