### ISSUE TITLE
Selecting the 1st date of every month when scrolling to another month

### ISSUE THREAD

**Issue by liuliangju** [jonathantribouharet/JTCalendar#310]
Could you tell me where should i call this method to get the Selecting the 1st date of every month when Horizontal scrolling to another month ,so  i can mark the 1st an extra color.

**Comment by doddyth** [comment]
I have the same issue, do you know how to do this? 

Thanks

**Comment by liuliangju** [comment]
@doddyth 
- (void)calendar:(JTCalendarManager *)calendar prepareDayView:(JTCalendarDayView *)dayView
{
    dayView.hidden = NO;
    
    // Other month
    if([dayView isFromAnotherMonth]){
        dayView.hidden = YES;
    }
    // Today
    else if([_calendarManager.dateHelper date:[NSDate date] isTheSameDayThan:dayView.date]){
        dayView.circleView.hidden = NO;
        dayView.circleView.backgroundColor = [UIColor blueColor];
        dayView.dotView.backgroundColor = [UIColor whiteColor];
        dayView.textLabel.textColor = [UIColor whiteColor];
    }
    //first day of month
    else if ([_calendarManager.dateHelper date:[_calendarManager.dateHelper firstDayOfMonth:dayView.date] isTheSameDayThan:dayView.date]) {
            dayView.circleView.hidden = NO;
            dayView.circleView.backgroundColor = [UIColor redColor];
            dayView.textLabel.textColor = [UIColor whiteColor];
    // Selected date
    }
