### ISSUE TITLE
Call a method when swiping horizontally to change the page

### ISSUE THREAD

**Issue by n4nachiket** [jonathantribouharet/JTCalendar#318]
Hello, I want to call some method when user swipes horizontally to change the month. I think overriding a method viewDidScroll in JTHorizontalCalendarView.m could do that. How can it be done?

**Comment by jonathantribouharet** [comment]
The delegate have `calendarDidLoadPreviousPage` and `calendarDidLoadNextPage` methods, if you want something more you will have to inherit from `JTHorizontalCalendarView`
