### ISSUE TITLE
How to set date limit in JTCalender?

### ISSUE THREAD

**Issue by dhirajdebut** [jonathantribouharet/JTCalendar#321]
I want to set date limit in JTCalender. As of now it shows dates more than of past year & more than a year ahead of current year. I want to set limit that it should show only dates of past 6 months & future 6 months. I am using swift language. Please suggest how to resolve this issue ?

**Comment by jonathantribouharet** [comment]
Check the Example project, `BasicViewController` and implement the method `canDisplayPageWithDate`.

**Comment by dhirajdebut** [comment]
Ok thanks this really worked for me
