### ISSUE TITLE
Date displayed incorrectly

### ISSUE THREAD

**Issue by Guodadada** [jonathantribouharet/JTCalendar#322]
![bad81ab5-031b-4aec-815b-21b64df70e51](https://cloud.githubusercontent.com/assets/16527069/21478931/7ae318b8-cb8b-11e6-935a-2382ba054b42.png)
![7776a856-e2b8-4c2a-bbcc-519726391673](https://cloud.githubusercontent.com/assets/16527069/21478932/7da77e5e-cb8b-11e6-80b1-83b6936972d9.png)

**Comment by jonathantribouharet** [comment]
It's because you don't manage the view correctly, the top calendar doesn't have a good height and overstep on the 2nd calendar.
You have to show 6 lines of days and not 5 because some month are on 6 weeks.
