### ISSUE TITLE
last several days in month in week mode disappear

### ISSUE THREAD

**Issue by doddyth** [jonathantribouharet/JTCalendar#324]
I have this problem, when i use week mode and then scrolling it until last week of the current month, somehow several days in last week missing from the week mode. 

As example, lets say current month have 31 days, and last week in calendar consist of 3 days in one row (29 - sun, 30 - mon, 31 - tue). These 3 days is somehow missing in week mode. So, after 28, it will go to the next month. Do you have any idea?

Thanks

**Comment by jonathantribouharet** [comment]
This day are they visible in month mode?
Do you have the problem in the Example project?
It may be related to how you have implemented `prepareDayView` method, for example in week mode if you go to the end of january the last week (with 29,30,31) is "considered" like being in february if you have the same logic as in `BasicViewController`. In this case it's just a logic / design problem.

**Comment by doddyth** [comment]
Sorry for getting back late.

Yeah! that seems the case! checked the example and yes, dayView.isFromAnotherMonth in BasicViewController is hidding the dayView. Thanks!
