### ISSUE TITLE
How to get the month name with year in swift 3

### ISSUE THREAD

**Issue by milishah259** [jonathantribouharet/JTCalendar#329]
menuItemView.text -> Value of type 'UIView' has no member 'text'

```
public func calendarBuildMenuItemView(_ calendar: JTCalendarManager!) -> UIView!
    {
        let label = UILabel.init()
        label.textAlignment = NSTextAlignment.center
        return label;
    }

public func calendar(_ calendar: JTCalendarManager!, prepareMenuItemView menuItemView: UIView!, date: Date!)
    {
        let dateFormatter : DateFormatter
        dateFormatter.dateFormat = "MMMM yyyy";
            
        dateFormatter.locale = calendarManager.dateHelper.calendar().locale;
        dateFormatter.timeZone = calendarManager.dateHelper.calendar().timeZone;
        menuItemView.text = dateFormatter.string(from: date)
 }
```

**Comment by rajdhakate** [comment]
instead of last line,
menuItemView.text = dateFormatter.string(from: date)

use
[(UILabel*) menuItemView setText:[dateFormatter stringFromDate:date]];

this is on objective c but get an idea and try to implement the same.

**Comment by milishah259** [comment]
Thank you so much but i solved it ... And my solution is 

      public func calendar(_ calendar: JTCalendarManager!, prepareMenuItemView menuItemView: UIView!, date: Date!)
       {
        for view in menuItemView.subviews {
            view.removeFromSuperview()
        }
        let label1 = UILabel(frame: CGRect(x: 80, y: 60, width:400, height: 21))
        label1.center = CGPoint(x: 130, y: 20)
        label1.textColor = UIColor.black
        label1.textAlignment = NSTextAlignment.center
        let dateFormatter1 = DateFormatter()
        dateFormatter1.dateFormat = "MMMM yyyy";
        let mydt = dateFormatter1.string(from: date)
        label1.text = mydt
        menuItemView.addSubview(label1)
    }

**Comment by milishah259** [comment]
Thank you so much ... but i solved it . And my solution is :

public func calendar(_ calendar: JTCalendarManager!, prepareMenuItemView menuItemView: UIView!, date: Date!)
    {
        for view in menuItemView.subviews {
            view.removeFromSuperview()
        }
        let label1 = UILabel(frame: CGRect(x: 80, y: 60, width:400, height: 21))
        label1.center = CGPoint(x: 130, y: 20)
        label1.textColor = UIColor.black
        label1.textAlignment = NSTextAlignment.center
        let dateFormatter1 = DateFormatter()
        dateFormatter1.dateFormat = "MMMM yyyy";
        let mydt = dateFormatter1.string(from: date)
        label1.text = mydt
        menuItemView.addSubview(label1)
    }

**Comment by milishah259** [comment]
Thank you so much ... but i solved it and my solution is :    

    public func calendar(_ calendar: JTCalendarManager!, prepareMenuItemView menuItemView: UIView!, date: Date!)
    {
        for view in menuItemView.subviews {
            view.removeFromSuperview()
        }
        let label1 = UILabel(frame: CGRect(x: 80, y: 60, width:400, height: 21))
        label1.center = CGPoint(x: 130, y: 20)
        label1.textColor = UIColor.black
        label1.textAlignment = NSTextAlignment.center
        let dateFormatter1 = DateFormatter()
        dateFormatter1.dateFormat = "MMMM yyyy";
        let mydt = dateFormatter1.string(from: date)
        label1.text = mydt
        menuItemView.addSubview(label1)
    }

**Comment by rajdhakate** [comment]
Good. so you can now close the thread.

**Comment by milishah259** [comment]
Yes.
