### ISSUE TITLE
JTCalendar Crash on Table View Cell

### ISSUE THREAD

**Issue by pateldhruv123100** [jonathantribouharet/JTCalendar#333]
When I m Scroll Next Month JTCalender Crash , Because of NsDate will Be nil.
Any one Can use JTCalender in TableView Cell??? 
http://prntscr.com/epryii

**Comment by jvashisht** [comment]
Hello @pateldhruv123100 did you solved your issue, i am facing the issue calender is not loading in the tableview cell. can you help me on this ??

**Comment by jonathantribouharet** [comment]
Hi,
using the calendar in a cell should not crash, have you tried the same code in the same controller but not in a cell?
It's probably because you try to display the calendar without initialise it:

```  
    _calendarManager = [JTCalendarManager new];
    _calendarManager.delegate = self;
    
    [_calendarManager setMenuView:_calendarMenuView];
    [_calendarManager setContentView:_calendarContentView];
    [_calendarManager setDate:[NSDate date]];
```

**Comment by jonathantribouharet** [comment]
It should work, I cannot say without having the complete code.
You could improve your code with:

```
(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{

	static NSString *CellIdentifier = @"cell";

	TableViewCell *cell = (TableViewCell *)[tableView dequeueReusableCellWithIdentifier:CellIdentifier];
	if (cell == nil) {
		cell = [[TableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier];
		[_calendarManager setContentView:cell.calenderView];
		cell.selectionStyle = UITableViewCellSelectionStyleNone;
	}

	[_calendarManager setDate:_todayDate];   

	return cell;
}
```

If you have only one calendar in the tableView and one manager, you can just bind them when you create the cell and not at each call of `cellForRowAtIndexPath`.
But it's depending of what you want to do.

**Comment by jvashisht** [comment]
Thanks got it!!
