### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by hassan8357** [jonathantribouharet/JTCalendar#336]
Why the 1.x version is support RTL and from 2.0 version it removed and doesn't support?

**Comment by hassan8357** [comment]
I've found workaround to solve this issue.

After configure calendar rotate contentView and weekDayView label 180 degree
`//Rotate contentView(Scroll View) 180 degree
        calendarManager.contentView.transform = CGAffineTransformMakeScale(-1.0, 1.0);
        
        //Rotate weekDayView label 180 degree
        for (UIView *contentViewSubview in calendarManager.contentView.subviews) {
            if ([contentViewSubview class] == [JTCalendarPageView class]) {
                for (UIView *view in contentViewSubview.subviews) {
                    if ([view class] == [JTCalendarWeekDayView class]) {
                        for (UIView *weekDayView in ((JTCalendarWeekDayView*)view).dayViews) {
                            weekDayView.transform = CGAffineTransformMakeScale(-1.0, 1.0);
                        }
                    }
                }
            }
        }`

Then you need to rotate dayView too. You can do that in method delegate **prepareDayView**
`//Rotate dayView 180 degree
    if ([CurrentLanguageKey isEqualToString:Arabic_Language_Key]) {
        dayView.transform = CGAffineTransformMakeScale(-1.0, 1.0);
    }`

**Comment by jonathantribouharet** [comment]
Sorry, the 1.x wasn't developed to support RTL neither.
