### ISSUE TITLE
podspec source_files includes everything

### ISSUE THREAD

**Issue by YuriSolodkin** [jonathantribouharet/JTCalendar#364]
Hi there,  

Is that line of the podspec correct?
`s.source_files  = 'JTCalendar/**/*'
`
It includes everything including Info.plist.

Should it be 

`s.source_files  = 'JTCalendar/**/*.{h,m}'` ?

**Comment by jonathantribouharet** [comment]
Hi,
both version are / were correct, yours is cleaner, in a recent merge with a PR I didn't see the info.plist file added.
Have you a problem with the pod?

**Comment by YuriSolodkin** [comment]
Sometimes I'm getting this issue, cannot replicate on demand, but always with JTCalendar:

`dyld: Library not loaded: @rpath/JTCalendar.framework/JTCalendar`

So I started to search and found that discussion on SO:

https://stackoverflow.com/questions/39160654/signing-errors-with-use-frameworks-and-unique-provisioning-profiles/39182887#39182887

I'm not sure they are related, but probably having *.{h,m} will be more straightforward.
I can see Info.plist in the pod folder.

**Comment by jonathantribouharet** [comment]
I release a new version `2.2.1`, but I already seen your bug with others libraries without finding a good reason. It seems to happen on projet where I manage multiple targets with a target depending of another target (I have an app and a core lib). The only solution I have found is to clear the projet and recompile.

**Comment by YuriSolodkin** [comment]
Thank you! Yes, that's exactly the scenario you're describing, I cannot find a good solution too.
