### ISSUE TITLE
I would like draw a circle in any day of the month through the array of days and with different colors, it is possible? Like this...

### ISSUE THREAD

**Issue by raffaelps** [jonathantribouharet/JTCalendar#39]
![calendario](https://cloud.githubusercontent.com/assets/1504226/5558114/c7aaa736-8d00-11e4-9074-dfe2b14fbc17.png)

**Comment by ryanhoo** [comment]
@raffaelps Have you made it? I want the same feature. I will have to finish it and launch a pull request if you didn't.

**Comment by raffaelps** [comment]
@ryanhoo sorry for the delay. I didn't finish it because I changed my project's requirements.

**Comment by palcalde** [comment]
@ryanhoo in case anyone needs the same, I have a forked version here: https://github.com/palcalde/JTCalendar that allows to customize the background view of any day via a new delegate I setted up. Take a look.

**Comment by ryanhoo** [comment]
@palcalde Thanks, I will check it out.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
