### ISSUE TITLE
Add Delegate 

### ISSUE THREAD

**Issue by f33chobits** [jonathantribouharet/JTCalendar#45]
Hi there, in some cases the calendar day view should not be allowed to select, I think it's better to have a delegate with a method whether we should select the date. The datasource didn't work as a datasource but as a delegate.Can we change the data source to delegate too?

**Comment by jonathantribouharet** [comment]
Delegate or datasource is a "name", it's just a protocol. At the beginning i didn't have `calendarDidDateSelected ` method so it was a datasource, I keep the name for compatibility with older version.

**Comment by f33chobits** [comment]
How about adding a protocal method
 -(BOOL)calendar:(JTCalendar)calendar shouldSelectDate:(NSDate *)date 
which could allow disabling some dates selection?

**Comment by jonathantribouharet** [comment]
I will do it soon.

**Comment by jonathantribouharet** [comment]
Sorry for the delay, I just added a new method `calendar:canSelectDate` for the delegate.
