### ISSUE TITLE
JTCalendar doesn't display current month, instead shows 2 months ago by default

### ISSUE THREAD

**Issue by ergodic1** [jonathantribouharet/JTCalendar#47]
Looking through the source, the only way I could find to select the current month when first loading was to perform these in sequence:

    [calendar loadNextMonth];
    [calendar loadNextMonth];
    [calendar reloadData];

This is due to the way it's loading two months either side of the current month, and doesn't scroll to the current month, but shows currentMonth - 2 months as the default calendar.

It seems to me that setCurrentDate should automatically scroll to the current month.

**Comment by jonathantribouharet** [comment]
It's probably because you don't call `[self.calendar reloadData];` in `viewDidAppear`.
Check the example project.

**Comment by ergodic1** [comment]
Correct, and it turns out that the two calls to [calendar loadNextMonth]; were not required (I was doing these in viewDidAppear.

Thanks!
