### ISSUE TITLE
add alpha animation for menu month view

### ISSUE THREAD

**Issue by f33chobits** [jonathantribouharet/JTCalendar#50]
Hi, @jonathantribouharet 
I add a alpha animation effect on the month menu view. The more the menu is close to the center of the screen, the greater the alpha is. I also leave a interface for setting the max alpha value and the min.This is the effect 
PR #52 

![jtcalendar-alpha](https://cloud.githubusercontent.com/assets/5186464/5951953/693e15b6-a7a9-11e4-93bd-04379b74302c.gif)

**Comment by yuriferretti** [comment]
Hi @f33chobits  I used this code and its crashing on deallocation because the KVO observers added to observe contentOffset property aren't deallocated correctly. I saw that your code correctly remove the observers on dealloc methods but both the object observed is nil on dealloc call, leading to removeObserver:forKeyPath not being executed.

**Comment by f33chobits** [comment]
Hi @yuriferretti 
Sorry, I forget to submit my fixing to this. This problem would come up because the parent view would call 'dealloc' ahead of the child day view whose 'delloc' method removing KVO Observer. I fixed it temporarily by removing observers in parent view's(contentView) dealloc, but that shouldn't be right. I think I should use NSNotificationCenter instead, which could decouple this complicated relationship between the parent view and the children view, what do you think about this?

**Comment by f33chobits** [comment]
Hey @yuriferretti .
Sorry I forgot to submit my fixing to this. This problem would come up because the menuView would call dealloc ahead of menuMonthView (parent view first). So I fixed this by enumerating and removing observers in menuView. But that shouldn't be right. I think I should use NSNotificationCenter instead, which would decouple the dependence bettween menuView and menuMonthView. What do you think about this?

**Comment by f33chobits** [comment]
Moved to #52

**Comment by jonathantribouharet** [comment]
Sorry, but i cannot accept this pull request for 2 reasons:
- first, you can just add a view over the `JTCalendarMenuView` which can reproduce the same effect, it will be cleaner and simpler
- i will never accept a code with a try catch

**Comment by f33chobits** [comment]
Try catch is indeed a bad solution,  but is there another way to check whether there is an kvo observer yet?

**Comment by jonathantribouharet** [comment]
From my experience, kvo is not a good thing to use in many case. In your code, it's even worse because the observer is the object itself. It's a ScrollView, you could just override layoutSubviews.

**Comment by f33chobits** [comment]
layoutSubviews is great! Thanks :+1:

**Comment by yuriferretti** [comment]
@f33chobits I just moved your KVO observing code to JTCalendarMenuView's private method configureConstraintsForSubviews as @jonathantribouharet  mentioned and it's working like a charm!!

**Comment by f33chobits** [comment]
:+1:
