### ISSUE TITLE
the date selected doesn't match

### ISSUE THREAD

**Issue by jiahao1994** [jonathantribouharet/JTCalendar#53]
I have this problem where the date i click on and displayed is not the same date. For example, if i clicked on 7th May, the console will display 6th May instead. 
![problem](https://cloud.githubusercontent.com/assets/5771429/5960184/a082b300-a80e-11e4-9888-8d80134329ff.png)

**Comment by jonathantribouharet** [comment]
It's because the time is UTC.

**Comment by jiahao1994** [comment]
how do i change the timezone to use the systemTimeZone? Sorry, only started to do iOS programming recently.

**Comment by jonathantribouharet** [comment]
self.calendar.calendarAppearance.calendar is a NSCalendar:
https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSCalendar_Class/
