### ISSUE TITLE
expensive for ReloadData, expensive for iphone Memory

### ISSUE THREAD

**Issue by XiangqiTu** [jonathantribouharet/JTCalendar#54]
when I need to reload current MonthView, I must reload `[self.contentView reloadData];` There isn't a convenient way to reload current MonthView,it cost much to reload the whole ContentView(`#define NUMBER_PAGES_LOADED 5 // Must be the same in JTCalendarView, JTCalendarMenuView, JTCalendarContentView`). NUMBER_PAGES_LOADED MonthViews will reload at the same time.

NUMBER_PAGES_LOADED change 5 to 3. the total Memory reduce about 10MB,and it become light.
But it much easier to load a white view .
![Memory 30MB](https://cloud.githubusercontent.com/assets/2850195/6037334/6da832f6-ac8d-11e4-85ca-055c0c25e972.jpeg)
![Unexpected UI](https://cloud.githubusercontent.com/assets/2850195/6037322/4aa4c4fe-ac8d-11e4-97f0-13fad8badb22.jpeg)

hope new source File  and effective Source File come out.

btw: I like JTCalendar very much, i learned a lot from you.thanks for sharing.
best regards!

**Comment by jonathantribouharet** [comment]
Hi,
`reloadData` is "heavy" and is supposed to be called only for load the calendar. I didn't think about changing the month view "in live" when i coded the calendar. Maybe you can try to call `reloadAppearance`.
I have to write a new version, more optimised but i don't have the time yet.

**Comment by XiangqiTu** [comment]
thx for your response .   :-).
I am waiting for you. Wish new codes coming soon. :-)

May be next words is a question:
each month events upload to server. when I slide to next/last month，I need to sync the currentMoth events from server, and update "Calendar UI" , present these events from server.

sync one month events and update the "Calendar UI",I need to reload `[self.contentView reloadData]`, but the`contentView` has  NUMBER_PAGES_LOADED monthViews to reload. it's "heavy" for me...

any better solution ？

**Comment by XiangqiTu** [comment]
May be I need to override your `reload` codes.

A ha, just do it.

thank you.

**Comment by jonathantribouharet** [comment]
Don't forget to disable the data cache
https://github.com/jonathantribouharet/JTCalendar#data-cache

And yes i recommend you to fork the project and do some change. The more simple is probbably to create a reload data event in JTCalendarDayView.
