### ISSUE TITLE
select date, need a transition animation.week mode need to show selected date accurately

### ISSUE THREAD

**Issue by XiangqiTu** [jonathantribouharet/JTCalendar#55]
When i selected date ·[self.calendar setCurrentDate:[NSDate date]]·，it's nice that has a transition animation.

week mode need to show selected date accurately.

when i selected one date and change mode to week mode, it's hard for me to find last selected date.

waiting for your new code.
thx for reading.
best regards!

**Comment by jonathantribouharet** [comment]
I don't see your question.
For the selected date i think you must read the Warning section: https://github.com/jonathantribouharet/JTCalendar#warning-1

**Comment by XiangqiTu** [comment]
I feel uneasy , because of the weak English ability ... ...
This issue is a suggestion about week-mode ， it need better expression.
