### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by athulgrg** [jonathantribouharet/JTCalendar#57]
Design is not working correctly on rotation, trying on iOS8 sdks with auto layout, even tried by forcing reloadAppearance on rotation, still couldn't get to work it. Attaching images here with... Any help will be appreciated and do keep up the good work.. :)

![ios simulator screen shot feb 9 2015 5 24 23 pm](https://cloud.githubusercontent.com/assets/10922256/6105774/e27e7198-b080-11e4-9b94-f1f4038849e9.png)

![ios simulator screen shot feb 9 2015 5 24 32 pm](https://cloud.githubusercontent.com/assets/10922256/6105780/f036874e-b080-11e4-9ed7-dbca397f439c.png)

**Comment by jonathantribouharet** [comment]
I just add in the last version of the README how to do it. Just call

    [self.calendar updatePage];

in `didRotateFromInterfaceOrientation` in your controller for manage the rotation.

**Comment by athulgrg** [comment]
Well the updatePage call updates the page but it consistently changes the month that is currently on display, like if we are in portrait and it is showing jan when we change to landscape it shows feb likewise, strictly it's not the expected behavior.... Do try to look into it... As of now i don't think the bug should be closed... Anyway thanks for the quick response... :)

**Comment by jonathantribouharet** [comment]
Sorry, my mistake it's not `updatePage` you have to call but `repositionViews`.

**Comment by athulgrg** [comment]
yay, good work (y). its good now... thank you for the response... saved me a lot of time... :)
