### ISSUE TITLE
Number of rows in JTCalendar view not including days row.

### ISSUE THREAD

**Issue by hirenpanchal1608** [jonathantribouharet/JTCalendar#59]
Hello

JTCalendar is very nice and customisable calendar for iOS.
It is currently displaying 6 rows.
I want to display only 5 rows in every months.

Is it possible to do this.? How.?
Help me.

Thanks in advance.

**Comment by jonathantribouharet** [comment]
In fact you can't because in some case you will need 6 rows (if the first day of the week is Sunday for example in March 2015).
