### ISSUE TITLE
Changing Layout Direction

### ISSUE THREAD

**Issue by sdtaheri** [jonathantribouharet/JTCalendar#60]
Hi,

It's a great calendar. The only thing I need is the ability to change the direction of layout. As you know some languages such as Persian or Arabic are written from right to left. I can change the numbers and text to Persian using locale property on NSDateFormatter objects. But the navigation should be exactly reversed so that it feels natural to Persian speaking users. I mean that swiping to right should go to next month instead of previous month. Also I need the days to lay themselves out from right to left in each row; let's say 1 is in the right most location and 7 is in the left most and then 8 is in the right most in the 2nd row and so on. I hope you get what I mean and could help me how to do it. @jonathantribouharet

**Comment by jonathantribouharet** [comment]
Ok, i see what i can do.

**Comment by jonathantribouharet** [comment]
I added the `readFromRightToLeft` option to calendarAppearence, just set it to `YES`and tell me if it's good, i may have miss something. Don't forget to update the pod with `pod update`.

**Comment by sdtaheri** [comment]
You are awesome man! I don't know how to thank you. I really didn't except you to update this soon. 
I checked. Essentially everything looks OK except for just a little thing. Now the next and previous is literally reversed. Now when we swipe to right, the "Next" page is being loaded. If you check the example you see that the Logs show something else. I think these two methods calls need updating somewhere. 

- (void)calendarDidLoadPreviousPage;
- (void)calendarDidLoadNextPage;

Other than this, everything works perfectly.
Je vous remercie autre fois! ;-)

**Comment by jonathantribouharet** [comment]
I hesitate about `calendarDidLoadPreviousPage` but i let it the way because it loads the previous page but not the previous month.
