### ISSUE TITLE
Unable to find day view as you displayed in screenshots

### ISSUE THREAD

**Issue by ShahVivek** [jonathantribouharet/JTCalendar#61]
![example](https://cloud.githubusercontent.com/assets/6389144/6223980/faa3c0e2-b699-11e4-8d90-fb7a2d7ee6cc.png)

I want to integrate calendar in my App,which includes MonthView,WeekView and DayView.
I find this JTCalendar very helpful for this but I am unable to find the functionality of DayView as it shown in screen shot.
Please help me if you have the solution.

**Comment by jonathantribouharet** [comment]
Sorry, it's not in the calendar because it's the design i used for a client, i cannot distribute it.
It's specific but pretty simple to reproduce but it's very specific to your data.

**Comment by ShahVivek** [comment]
Ok no problem. I will manage it.
Thanks :-)
