### ISSUE TITLE
Change circle for other form

### ISSUE THREAD

**Issue by jcamejo** [jonathantribouharet/JTCalendar#63]
Hi!

Specifficaly,  i'll like to fill the entire day square with any color and not only the circle.

There is anyway i can do that?

Thanks

**Comment by jonathantribouharet** [comment]
No sorry, currently but I keep the idea for a next version.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

You can subclass JTCalendarDayView and do whatever you want.
