### ISSUE TITLE
Different values for ratioContentMenu

### ISSUE THREAD

**Issue by sdtaheri** [jonathantribouharet/JTCalendar#66]
Hi,

Sorry for bothering you this much. I know you've done a great job and just want to help you make it the best.

If we set any value other than 1.0 or 2.0 for ratioContentMenu we have some problems in scrolling in menuView.

1) For any value more than 1.0 and less than 2.5 except 2.0 we have a glitch in scrolling to next month. 

2) For any value more than 2.5, the scrolling to next month never happens.

The GIFs are in the mentioned order.

![1](https://cloud.githubusercontent.com/assets/7237058/6263035/8a1dcc22-b825-11e4-87e9-b1d52a293fd7.gif)

![2](https://cloud.githubusercontent.com/assets/7237058/6263040/9863cde0-b825-11e4-8ead-0d25f25beadb.gif)

**Comment by jonathantribouharet** [comment]
Thank you, I noticed this bug, it's because I use `pagingEnabled` of the UIScrollView.
#65
