### ISSUE TITLE
Performance during initialization

### ISSUE THREAD

**Issue by jlindenbaum** [jonathantribouharet/JTCalendar#68]
Thanks for a great control.

I'm wondering if there's anything I can do to improve the performance of the calendar? There's a noticable lag (1000ms +) when the views are initially instantiated. If I'm doing my math right there are 5 months created at a time, each containing 30 (or more) day views, which in themselves have 3 views? So there's about 450 views being created, styled, laid out during initialization?

Is there any way that I can defer this view creation until we call `[calendar setMenuMonthsView: _myCalendarMonthView];` and `[calendar setContentView: _myCalendarContentView];`?

It would be ideal if this initialization could be non-blocking and I get notified in the delegate that the calendar is ready to show. Obviously that's a problem with those views having to lay themselves out on the UI thread.

I've tried moving some things around myself, but always end up with a `CALayer position contains NaN: [nan 15]` crash. It'll take me longer to try and dig through this than just asking you.

Any help would be appreciated.

Currently this is how my `viewDidLoad` initializes the calendar

```
-(void) initializeCalendar {
    calendar = [JTCalendar new];
    
    // start day of week
    SevenCompany *company = [delegate company];
    NSNumber *startDay = [company startWeekOn];
    calendar.calendarAppearance.calendar.firstWeekday = ([startDay intValue] + 1); // our offset starts at 0, theirs at 1
    
    // colours for selector bubbles
    UIColor *primaryAlpha = [[WhiteLabel sharedInstance] getColor:@"color-primary-alpha"];
    calendar.calendarAppearance.dayCircleColorSelected = [[WhiteLabel sharedInstance] getColor:@"color-primary"];
    calendar.calendarAppearance.dayCircleColorToday = primaryAlpha;
    calendar.calendarAppearance.dayCircleColorSelectedOtherMonth = primaryAlpha;
    calendar.calendarAppearance.dayCircleColorTodayOtherMonth = primaryAlpha;
    
    calendar.calendarAppearance.menuMonthTextColor = [UIColor whiteColor];
    
    [calendar setMenuMonthsView:_calendarMenu];
    [calendar setContentView:_calendarContent];
    [calendar setCurrentDate:currentDate];
    [calendar setCurrentDateSelected:currentDate];
    [calendar setDataSource:self];
}
```

**Comment by jonathantribouharet** [comment]
I try to do my best for avoid latency (first time I used autolayout), the only thing I see I can do is subclass UIScrollView (which is a lot better) or even rewrite using a GLKView but I don't have the time yet.
But if you have a lag of 1000ms you have a problem because with the Example project it takes 250ms to load (between before viewDidLoad and after viewDidAppear).
If you want defer the view creation, just create the view when you need.

**Comment by jlindenbaum** [comment]
I solved it for now by not using IB to instantiate the calendar views hidden in the view. Instead I am instantiating in the background and start loading my events from the network after this instantiation, once the network is done the calendar views are shown.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.

This bug should be gone.
