### ISSUE TITLE
Only display dates from a starting date

### ISSUE THREAD

**Issue by axelkennedal** [jonathantribouharet/JTCalendar#71]
I'm developing an app in which the user is supposed to select a future date. It would be really nice if there was a property (e.g. NSDate *startdate) on the calendar that made sure no dates earlier than that are displayed. (As of now I have to display an alert informing the user that previous dates should not be selected)

**Comment by HaloZero** [comment]
I solved this by adding my own pan gesture recognizer, this allowed me to control what dates it went to. you have to implement your own swipe up / down handling though.

**Comment by revolter** [comment]
@HaloZero, could you provide some example code or reference?

**Comment by HaloZero** [comment]
This might not be valid code, but should be approximately what you need. My code only works for changing months only though, not panning weeks. 

UIPanGestureRecognizer *panGesture = [[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(swipeToChangeMonth:)];
[self.calendarContentView addGestureRecognizer:panGesture];
     
 - (void)swipeToChangeMonth:(UIPanGestureRecognizer *)sender  {
    CGPoint v = [sender velocityInView:sender.view];
    if( (abs(v.x) >= 300) && !self.panningCalendar)
    {
        self.panningCalendar = YES;
        [sender cancelsTouchesInView];

        NSDate *currentCalendarDate = // some date

        NSDate *firstMessageDate = // some code to get the first message date

        if(v.x > 0) {
            if (currentCalendarDate.year > firstMessageDate.year || currentCalendarDate.month > firstMessageDate.month) {
                [self.calendar loadPreviousMonth];
            }

        } else {
            NSDate *today = [NSDate date];
            if (currentCalendarDate.year < today.year || currentCalendarDate.month < today.month) {
                [self.calendar loadNextMonth];
            }

        }
    }
}

**Comment by revolter** [comment]
I don't use the week mode view, so it's ok. Thanks!

**Comment by HaloZero** [comment]
@revolter I would mention that I discovered that I needed to also add something similiar to the month view or else you can gesture normally there.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
