### ISSUE TITLE
Selected day animation when switching views

### ISSUE THREAD

**Issue by nanoxd** [jonathantribouharet/JTCalendar#73]
I'm not sure if this is intended behavior and could not find anything in the issues. When a day is selected, a red circle appears. When you switch to a week view using the example code, the selected day has an animation that occupies the entire screen:
![calendar_bug](https://cloud.githubusercontent.com/assets/1889575/6333799/ec461f22-bb44-11e4-8297-cd30f38f5690.gif)

The current date on the other hand enlarges itself a tiny amount and reverts to normal. Is this expected behavior? If so, what is the recommended way to remove the animation?

**Comment by jonathantribouharet** [comment]
I don't have this bug, do you try the last version? The animation is not on the red dot but on `calendarContentView` so you can change the animation yourself.

**Comment by nanoxd** [comment]
Yes, I installed the pod yesterday. `Podfile.lock` has it listed as 1.1.17

**Comment by jonathantribouharet** [comment]
I don't have the button "Switch view" in my example, like i said you can use the transition you want.
