### ISSUE TITLE
Selecting the 1st date of every month when navigating to another month

### ISSUE THREAD

**Issue by manikkalra** [jonathantribouharet/JTCalendar#74]
I'm not using the JTCalendarMenuView in my app due to space constraints. Instead I show the selected date on the navigation bar of my app. Is there anyway to mimic the stock iOS calendar app behavior ? 
That is, when you swipe to another month, the selected date changes to the 1st of that month.

**Comment by jonathantribouharet** [comment]
You have `calendarDidLoadPreviousPage` and `calendarDidLoadNextPage` method for your delegate and you can use

    [NSNotificationCenter defaultCenter] postNotificationName:@"kJTCalendarDaySelected" object:date];

To select the date you want.

**Comment by manikkalra** [comment]
Thank you!

Any tips on how to get the date for the first of every month when you go forward or back?

**Comment by jonathantribouharet** [comment]
I have this 2 functions in my code:

    - (NSDate *)beginningOfMonth:(NSDate *)date
    {
        NSCalendar *calendar = self.calendarManager.calendarAppearance.calendar;
        NSDateComponents *componentsCurrentDate = [calendar components:NSCalendarUnitYear|NSCalendarUnitMonth|NSCalendarUnitDay|NSCalendarUnitWeekday|NSCalendarUnitWeekOfMonth fromDate:date];
        
        NSDateComponents *componentsNewDate = [NSDateComponents new];
        
        componentsNewDate.year = componentsCurrentDate.year;
        componentsNewDate.month = componentsCurrentDate.month;
        componentsNewDate.weekOfMonth = 1;
        componentsNewDate.weekday = calendar.firstWeekday;
        
        return [calendar dateFromComponents:componentsNewDate];
    }

    - (NSDate *)beginningOfWeek:(NSDate *)date
    {
        NSCalendar *calendar = self.calendarManager.calendarAppearance.calendar;
        NSDateComponents *componentsCurrentDate = [calendar components:NSCalendarUnitYear|NSCalendarUnitMonth|NSCalendarUnitDay|NSCalendarUnitWeekday|NSCalendarUnitWeekOfMonth fromDate:date];
        
        NSDateComponents *componentsNewDate = [NSDateComponents new];
        
        componentsNewDate.year = componentsCurrentDate.year;
        componentsNewDate.month = componentsCurrentDate.month;
        componentsNewDate.weekOfMonth = componentsCurrentDate.weekOfMonth;
        componentsNewDate.weekday = calendar.firstWeekday;
        
        return [calendar dateFromComponents:componentsNewDate];
    }

**Comment by manikkalra** [comment]
I have something similar too. What I was asking was if there was someway to know which month you are navigating to when you call calendarDidLoadPreviousPage and calendarDidLoadNextPage?

**Comment by jonathantribouharet** [comment]
You have `self.calendar.currentDate`

**Comment by Ganesh210-Naicker** [comment]
@jonathantribouharet  Could you tell me where should i call this method to get the Selecting the 1st date of every month when navigating to another month ,because i have used your JTCalendar and it is very useful to me and i have done two weeks mode method too.

Check this link:http://stackoverflow.com/questions/29160361/how-to-implement-calendar-view-in-two-weeks-modeused-jtcalendar-example

**Comment by liuliangju** [comment]
@Ganesh210-Naicker  have you solved the issue,  Could you tell me where should i call this method to get the Selecting the 1st date of every month when navigating to another month

**Comment by liuliangju** [comment]
@manikkalra @Ganesh210-Naicker  have you solved the issue, Could you tell me where should i call this method to get the Selecting the 1st date of every month when navigating to another month
