### ISSUE TITLE
Main thread locking on mode switch (in simulator)

### ISSUE THREAD

**Issue by HaloZero** [jonathantribouharet/JTCalendar#75]
I've noticed that when you change modes and change the height of the contentView you will get a noticeable main thread lag immediately after the animation is done. It lasts for quite a bit afterwards and blocks everything.

Not entirely sure what's causing it and I'm going to investigate but I figure I should bring it up here. You can replicate it in your example project.

So here's the big gotcha: it only happens on the simulator. I can't seem to replicate it on the device.

**Comment by jonathantribouharet** [comment]
Maybe it's depend on the iOS version.

**Comment by HaloZero** [comment]
The simulator is running iOS 8.1 and my device is running iOS 8.1.3

**Comment by HaloZero** [comment]
Looks like iOS 7.1 simulator works fine, so maybe Xcode release with iOS 8.2 will fix everything.

**Comment by HaloZero** [comment]
Fixed in Xcode 6.2 in the iOS 8.2 simulator

**Comment by jonathantribouharet** [comment]
Thanks for the update.
