### ISSUE TITLE
Missing calendar month and year

### ISSUE THREAD

**Issue by kpysniak** [jonathantribouharet/JTCalendar#76]
Hi,

I'm adding the calendar using this code:

{
  - (void)viewDidLoad
  {
    [super viewDidLoad];
    
    self.calendar = [JTCalendar new];
    
    {
        self.calendar.calendarAppearance.calendar.firstWeekday = 7; // Sunday == 1, Saturday == 7
        self.calendar.calendarAppearance.dayCircleRatio = 9. / 10.;
        self.calendar.calendarAppearance.ratioContentMenu = 2.;
        self.calendar.calendarAppearance.focusSelectedDayChangeMode = YES;
        
        // Customize the text for each month
        self.calendar.calendarAppearance.monthBlock = ^NSString *(NSDate *date, JTCalendar *jt_calendar){
            NSCalendar *calendar = jt_calendar.calendarAppearance.calendar;
            NSDateComponents *comps = [calendar components:NSCalendarUnitYear|NSCalendarUnitMonth fromDate:date];
            NSInteger currentMonthIndex = comps.month;
            
            static NSDateFormatter *dateFormatter;
            if(!dateFormatter){
                dateFormatter = [NSDateFormatter new];
                dateFormatter.timeZone = jt_calendar.calendarAppearance.calendar.timeZone;
            }
            
            while(currentMonthIndex <= 0){
                currentMonthIndex += 12;
            }
            
            NSString *monthText = [[dateFormatter standaloneMonthSymbols][currentMonthIndex - 1] capitalizedString];
            
            NSLog(@"Month block called with: %@", [NSString stringWithFormat:@"%ld\n%@", comps.year, monthText]);
            return [NSString stringWithFormat:@"%ld\n%@", comps.year, monthText];
        };
        
    }

    [self.calendar setMenuMonthsView:self.calendarMenuView];
    [self.calendar setContentView:self.calendarContentView];
    [self.calendar setDataSource:self];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    [self.calendar reloadData];
 }

}

And it works just fine.

However, no label of what month or year the selected period is. How could I include those?

Thanks! :)

**Comment by jonathantribouharet** [comment]
Use `self.calendar.currentDateSelected` for have the selected date, after you can create your label and add it where you want.
