### ISSUE TITLE
Only show weeks required to see whole month

### ISSUE THREAD

**Issue by Objective-Zero** [jonathantribouharet/JTCalendar#77]
Hi as I was browsing through the library I notice you have a constant 6 for initializing the weeks for each month. However this draws an unnecessary week or two for each month depending if there are 4 or 5 weeks. Is there any easy way to modify the library to only show the required amount to see the whole month?

This would save space on the screen and would be more efficient. I tried doing my own approach however it didn't work since I do not know the hierarchy of the library very well. Let me know.

**Comment by jonathantribouharet** [comment]
It's because some months require have 6 weeks (March 2015 if you week start the Monday).

**Comment by Objective-Zero** [comment]
Ah ok, in that case can we dynamically load that value? If a month only has 4 weeks, can it just load 6 weeks and not the 6?

**Comment by jonathantribouharet** [comment]
I don't see how you want to do that, in a visual way.
If the height of the calendar change for each month, it means you must have a transition for changing the height of the calendar and I don't think that a calendar where the height increase and decrease each time the user change the month is really pleasant to see.
And it will force to update the layout, the performance are currently not great so with this it will be worse.

**Comment by Objective-Zero** [comment]
I know the main calendar app on the iPhone does this and they simply use UIView animations to make the adjacent tableview for that day's events to be bigger or smaller. Wouldn't this make it more efficient though? Instead of loading 6 objects every time, you theoretically could be loading only 4 or 5 when necessary.

**Comment by jonathantribouharet** [comment]
The iPhone calendar use vertical scroll, in this case it's obvious they have to do this.
You will have less elements to load but the animation have a heavy cost.
With my system, the user have a control on the scroll, with your either the user control the scroll and during the scroll you have to resize the calendar or the user can't and you do your animation.
In both case, you will have performance issues and I still don't think this is a good idea for the user experience.
I recommend you to fork the project and add your own changes, the lib is small enough to understand it.

**Comment by iD3v3lop3r** [comment]
Even I am facing this issue.
@bchessin have you solved this issue?
@jonathantribouharet have you fixed this issue ? If yes please provide the code to fix this issue.
