### ISSUE TITLE
View Layout on rotation

### ISSUE THREAD

**Issue by adozenlines** [jonathantribouharet/JTCalendar#78]
View layout on rotation with changing widths cause a layout and alignment issue via auto layout. Manually scrolling the view resolves the issue. This could be a bug in the contentOffset calculation.

**Comment by jonathantribouharet** [comment]
Try to call `[self.calendar repositionViews]` in `viewDidLayoutSubviews`.

**Comment by adozenlines** [comment]
Thanks.
