### ISSUE TITLE
How do i integrate this JTCalendar to my existing project??? please help

### ISSUE THREAD

**Issue by nnaavveenn35** [jonathantribouharet/JTCalendar#79]
I  have created a new project  and i wanna show JTCalendar over there(UIViewController - storyboard)
How do implement that?? when i tried it showing this error

Undefined symbols for architecture arm64: "_OBJC_CLASS_$_JTCalendar",

**Comment by artemkalinovsky** [comment]
1. add pod 'JTCalendar' to your podfile and update(intalll) pods
OR
download zip and add JTCalendar folder to your project
2. Add two new UIViews on you existing view (set custom class for one JTCalendarMenuView and JTCalendarContentView for other one).
3. Add this show outlets to your view controller
@property (weak, nonatomic) IBOutlet JTCalendarMenuView *calendarMenuView;
@property (weak, nonatomic) IBOutlet JTCalendarContentView *calendarContentView;
and connect them to your views in storyboard.
4. Follow Usage section from README of JTCalendar

**Comment by nnaavveenn35** [comment]
thanks i have made it yesterday..sorry for late reply..but when i load the same in UIPageViewController build on UIScrollView then i can see my calendar in all pages instead of one page.How to solve this issue .

**Comment by jonathantribouharet** [comment]
Check #31

**Comment by nnaavveenn35** [comment]
I have added that but still i have same problem

**Comment by nnaavveenn35** [comment]
My calendar is in third page (uipageviewcontroller).so when i load that uipageviewcontroller i can see calendar on my first,second and third page.  Once i reach third page  and swiping back to second or first page then calendar is not there..

**Comment by nnaavveenn35** [comment]
please check this link for flow

https://drive.google.com/file/d/0B6caVk8MnBVad0hZUE12TFpleHM/view?usp=sharing

**Comment by nnaavveenn35** [comment]
i have commented 

[self.calendar reloadData];


in viewdidappear()

then its working... is there any problem with commenting this?

**Comment by maurovz** [comment]
artemkalinovsky's answer did it for me. I needed to add the subviews and assign them the correct class then connect them to an IBOutlet
