### ISSUE TITLE
Message to a deallocated JTCalendar Object

### ISSUE THREAD

**Issue by polqf** [jonathantribouharet/JTCalendar#8]
I have a navigation controller with 3 VC, one of them has a button that goes to the VC where the calendar is displayed. Once there, if I go back it crashes.
The reason is that is sending a message to the calendar (JTCalendar object), that was deallocated. The message is “scrollViewDidScroll:” and it is a UIScrollViewDelegate method.

I have been trying a lot of things, but nothing works. I was wondering if you know if there is somewhere in your code where I can prevent calling it when the calendar is deallocated.

Here you have the Zombie message:
-[JTCalendar scrollViewDidScroll:]: message sent to deallocated instance 0x1740933d0

**Comment by sadiqshaikh** [comment]
This bug is present now . I am using storyboard and it crashed after pressing back giving 
[JTCalendar scrollViewDidScroll:]: message sent to deallocated instance 0x7faf7d1df920
Thanks

**Comment by sadiqshaikh** [comment]
Yeah its working now  . checked your revision on 15 Nov which had a fix by adding dealloc

Thanks
