### ISSUE TITLE
Clone Appearance Of Screenshot

### ISSUE THREAD

**Issue by FPWebSystems** [jonathantribouharet/JTCalendar#82]
Hi,
thank you for your great calendar!

I would appreciate it if you just told me how to change the appearance of you calendar like this: https://github.com/jonathantribouharet/JTCalendar/blob/master/Screens/example.png

Also how to implement the nice table below the month view.

Thank you in advance!

**Comment by RokasAug** [comment]
Yes, what you use for that table below calendar?

**Comment by RokasAug** [comment]
I have used this project DayView above JTCalendar: https://github.com/muhku/calendar-ui

**Comment by jonathantribouharet** [comment]
Sorry, it's a specific code that I used for a client project, I can't share it with you. But it depend a lot of your usage of event, I used event from an API, so even with my code you won't go far.
