### ISSUE TITLE
Past days color of current month.

### ISSUE THREAD

**Issue by hirenpanchal1608** [jonathantribouharet/JTCalendar#85]
Hello JT,
Such a great work in JTCalendar,

I want to change colour of past days of current month in such a way that a user is able to know that this is the past day and can not selected,

I mean past day of current month can not be selected and colour is also just like as disabled button.

Can you please help me.
Thank you.

**Comment by jonathantribouharet** [comment]
Sorry I don't have implemented this feature, but I can be simply done by adding a condition in `JTCalendarDayView.m` in `setSelected` method.

**Comment by jonathantribouharet** [comment]
I just release a new version.
Check the Example project.
