### ISSUE TITLE
On the Example project, dates that have events are not shown with a dot

### ISSUE THREAD

**Issue by tartur** [jonathantribouharet/JTCalendar#86]
While playing with the Example App I remarked that no date had dots even the dates that have associated events. I debugged and I saw that the reloadData() calls calendarHaveEvent() with dates either in the future or in the past but never dates that are in the current month.

I did not push my investigations further but it seems weird for me. May be it is an optimization that interfer with the main feature or a too big offset.

**Comment by jonathantribouharet** [comment]
Thank you, it was just a mistake in the example code. I was calling `reloadData` method before `createRandomEvents`, so when the calendar load the data it find nothing, and there is a cache (check the README) so the first 5 month loaded don't have any event.

**Comment by tartur** [comment]
thx :)
