### ISSUE TITLE
Scroll week view on button click

### ISSUE THREAD

**Issue by ankitgoyalapplify** [jonathantribouharet/JTCalendar#89]
Hello,

I am using loadPreviousMonth function to load previous month on button click. I just wants to know whether I can load previous or next week in the same manner or not ? If yes, please describe how ??

**Comment by jonathantribouharet** [comment]
Update to the last version (few minutes ago).

I rename `loadPreviousMonth` in loadPreviousPage, it loads the previous page and not the previous month.
So when you're in "month mode" it loads the previous month and when you are in "week mode" it loads the previous week.

**Comment by ankitgoyalapplify** [comment]
Thank you JT :)
