### ISSUE TITLE
Hide previous or next month dates from current month

### ISSUE THREAD

**Issue by ankitgoyalapplify** [jonathantribouharet/JTCalendar#90]
Hello JT,

Can you please describe how can I hide previous or next month dates from current month and only show the dates or current month.

**Comment by jonathantribouharet** [comment]
Sorry, you can't.

**Comment by Praphin** [comment]
Can  u guys add above feature..

**Comment by felixdkatt** [comment]
Can you do this by changing the font color for days not in current month to clear color?
