### ISSUE TITLE
Display list of events

### ISSUE THREAD

**Issue by kiahop** [jonathantribouharet/JTCalendar#91]
Hello and thanks for sharing this great calendar code.   
I was able to add the control into my project, but was wondering if you happen to have any sample code to display List of Events for the selected day as shown in this image.  Any assistance is greatly appreciated.

Kia

![screen shot 2015-03-11 at 1 27 38 am](https://cloud.githubusercontent.com/assets/10413220/6592680/34d5be14-c78e-11e4-8426-804326c8d9a9.png)

**Comment by jonathantribouharet** [comment]
Sorry, it's a specific code that I used for a client project, I can't give it to you.
