### ISSUE TITLE
Disable past days, User should not able to select past days

### ISSUE THREAD

**Issue by hirenpanchal1608** [jonathantribouharet/JTCalendar#98]
Hello,

I want to disable past days,
User should not able to select past days,

Example : Current date is 20 March 2015,
So user should not able to select days till 19 March 2015.

Thank is advance.

**Comment by jonathantribouharet** [comment]
It's currently not possible. I just have to add a method to the delegate for that. I will do that quickly.

**Comment by hirenpanchal1608** [comment]
Ok, 
Thanks for reply.

**Comment by jonathantribouharet** [comment]
I just added a new method `calendar:canSelectDate` for the delegate.

**Comment by hirenpanchal1608** [comment]
Thanks a lot for quick update.

**Comment by nnaavveenn35** [comment]
Can you please give one example code to disable previous dates?

**Comment by hirenpanchal1608** [comment]
Hello JT,

Example for disable past days,

Suppose JTCalendar is currently showing MARCH-2015,
And today's s date is 15 MARCH 2015,
So All dates before 15 MARCH 2015 should be disabled, Color of this dates
should be same as previous month's date color.
User can not able to select dates before 15 MARCH 2015.
